// 南瓜家英文歌曲大冒險 — 歌單資料
// 每首歌資料結構：
//   owner / ownerColor / ownerAccent — 家庭成員與配色
//   title / artist / genre / year / album — 基本資料
//   story / meaning — 故事與意境（含注音）
//   task / practice / celebrate — 活動提示
//   keyLyrics — 精選歌詞片段（英 + 中含注音）
//   basicVocab / advancedVocab — 12 + 8 單字（含詞性、音標、注音、例句）
//   mission — 親子任務
window.APP_SONGS = [
  {
    slug: "way-back-into-love",
    owner: "南瓜爸爸",
    ownerColor: "#ff7a59",
    ownerAccent: "#cf4c3a",
    title: "Way Back Into Love",
    titleZh: "回到愛的路",
    titleZhRuby: "<ruby>回<rt>ㄏㄨㄟˊ</rt></ruby><ruby>到<rt>ㄉㄠˋ</rt></ruby><ruby>愛<rt>ㄞˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>路<rt>ㄌㄨˋ</rt></ruby>",
    artist: "Hugh Grant & Haley Bennett",
    genre: "Movie Ballad",
    year: "2007",
    album: "Music and Lyrics 電影原聲帶",
    creator: "Adam Schlesinger",
    cover: "assets/covers/Way%20Back%20Into%20Love.jpg",
    mp3: "assets/mp3/Way%20Back%20Into%20Love.mp3",
    lyricsDownload: "file:///Users/chennanhong/Desktop/AI%20%E8%82%B2%E5%85%92/%E8%8B%B1%E6%96%87%E6%AD%8C%E6%9B%B2/pumpkin_v3/02_%E6%AD%8C%E6%9B%B2%E5%AD%B8%E7%BF%92%E6%9C%AC/01_Way_Back_Into_Love.html",
    youtube: "https://www.youtube.com/watch?v=0bwWy67MsOU&list=RD0bwWy67MsOU&start_radio=1",
    genreDesc: "<ruby>流<rt>ㄌㄧㄡˊ</rt></ruby><ruby>行<rt>ㄒㄧㄥˊ</rt></ruby><ruby>抒<rt>ㄕㄨ</rt></ruby><ruby>情<rt>ㄑㄧㄥˊ</rt></ruby>(Pop Ballad)。<ruby>鋼<rt>ㄍㄤ</rt></ruby><ruby>琴<rt>ㄑㄧㄣˊ</rt></ruby><ruby>輕<rt>ㄑㄧㄥ</rt></ruby><ruby>輕<rt>˙ㄑㄧㄥ</rt></ruby><ruby>帶<rt>ㄉㄞˋ</rt></ruby><ruby>路<rt>ㄌㄨˋ</rt></ruby>，<ruby>男<rt>ㄋㄢˊ</rt></ruby><ruby>女<rt>ㄋㄩˇ</rt></ruby><ruby>合<rt>ㄏㄜˊ</rt></ruby><ruby>唱<rt>ㄔㄤˋ</rt></ruby>，<ruby>溫<rt>ㄨㄣ</rt></ruby><ruby>柔<rt>ㄖㄡˊ</rt></ruby><ruby>又<rt>ㄧㄡˋ</rt></ruby><ruby>甜<rt>ㄊㄧㄢˊ</rt></ruby><ruby>蜜<rt>ㄇㄧˋ</rt></ruby>。",
    meaning: "<ruby>主<rt>ㄓㄨˇ</rt></ruby><ruby>角<rt>ㄐㄩㄝˊ</rt></ruby><ruby>心<rt>ㄒㄧㄣ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby><ruby>受<rt>ㄕㄡˋ</rt></ruby><ruby>過<rt>ㄍㄨㄛˋ</rt></ruby><ruby>傷<rt>ㄕㄤ</rt></ruby>，<ruby>不<rt>ㄅㄨˋ</rt></ruby><ruby>敢<rt>ㄍㄢˇ</rt></ruby><ruby>再<rt>ㄗㄞˋ</rt></ruby><ruby>愛<rt>ㄞˋ</rt></ruby>。<ruby>這<rt>ㄓㄜˋ</rt></ruby><ruby>首<rt>ㄕㄡˇ</rt></ruby><ruby>歌<rt>ㄍㄜ</rt></ruby><ruby>說<rt>ㄕㄨㄛ</rt></ruby>：「<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>找<rt>ㄓㄠˇ</rt></ruby><ruby>到<rt>ㄉㄠˋ</rt></ruby><ruby>回<rt>ㄏㄨㄟˊ</rt></ruby><ruby>到<rt>ㄉㄠˋ</rt></ruby><ruby>愛<rt>ㄞˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>路<rt>ㄌㄨˋ</rt></ruby>！」",
    story: "這首歌像是在說，一個人曾經受傷、把心關起來，後來又慢慢想回到愛和希望裡面。",
    task: "一邊聽歌，一邊找出和心情、希望、方向有關的字，最後全家一起說一句鼓勵的話。",
    practice: "I can start again. I can open my heart. I can find a way back into love.",
    celebrate: "南瓜爸爸的新選曲揭曉！這首歌溫柔又有希望感，很適合一家人一起慢慢唱。",
    keyLyrics: [
      { en: "I've been lonely for so long.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>已<rt>ㄧˇ</rt></ruby><ruby>經<rt>ㄐㄧㄥ</rt></ruby><ruby>孤<rt>ㄍㄨ</rt></ruby><ruby>單<rt>ㄉㄢ</rt></ruby><ruby>了<rt>˙ㄌㄜ</rt></ruby><ruby>好<rt>ㄏㄠˇ</rt></ruby><ruby>久<rt>ㄐㄧㄡˇ</rt></ruby>。" },
      { en: "I've been watching but the stars refuse to shine.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>直<rt>ㄓˊ</rt></ruby><ruby>看<rt>ㄎㄢˋ</rt></ruby><ruby>著<rt>˙ㄓㄜ</rt></ruby>，<ruby>但<rt>ㄉㄢˋ</rt></ruby><ruby>星<rt>ㄒㄧㄥ</rt></ruby><ruby>星<rt>˙ㄒㄧㄥ</rt></ruby><ruby>不<rt>ㄅㄨˋ</rt></ruby><ruby>肯<rt>ㄎㄣˇ</rt></ruby><ruby>發<rt>ㄈㄚ</rt></ruby><ruby>光<rt>ㄍㄨㄤ</rt></ruby>。" },
      { en: "All I wanna do is find a way back into love.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>只<rt>ㄓˇ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>找<rt>ㄓㄠˇ</rt></ruby><ruby>到<rt>ㄉㄠˋ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>條<rt>ㄊㄧㄠˊ</rt></ruby><ruby>回<rt>ㄏㄨㄟˊ</rt></ruby><ruby>到<rt>ㄉㄠˋ</rt></ruby><ruby>愛<rt>ㄞˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>路<rt>ㄌㄨˋ</rt></ruby>。" },
      { en: "And if I open my heart again...", zh: "<ruby>如<rt>ㄖㄨˊ</rt></ruby><ruby>果<rt>ㄍㄨㄛˇ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>再<rt>ㄗㄞˋ</rt></ruby><ruby>次<rt>ㄘˋ</rt></ruby><ruby>打<rt>ㄉㄚˇ</rt></ruby><ruby>開<rt>ㄎㄞ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>心<rt>ㄒㄧㄣ</rt></ruby>……" },
      { en: "I hope that you'll be there for me in the end.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>希<rt>ㄒㄧ</rt></ruby><ruby>望<rt>ㄨㄤˋ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>最<rt>ㄗㄨㄟˋ</rt></ruby><ruby>後<rt>ㄏㄡˋ</rt></ruby><ruby>會<rt>ㄏㄨㄟˋ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>身<rt>ㄕㄣ</rt></ruby><ruby>旁<rt>ㄆㄤˊ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "love", type: "名詞", ph: "/lʌv/", zh: "<ruby>愛<rt>ㄞˋ</rt></ruby>", ex: "I love you.（我愛你）" },
      { en: "star", type: "名詞", ph: "/stɑːr/", zh: "<ruby>星<rt>ㄒㄧㄥ</rt></ruby><ruby>星<rt>˙ㄒㄧㄥ</rt></ruby>", ex: "Shining star.（閃亮的星星）" },
      { en: "cloud", type: "名詞", ph: "/klaʊd/", zh: "<ruby>雲<rt>ㄩㄣˊ</rt></ruby>", ex: "A big cloud.（一朵大雲）" },
      { en: "heart", type: "名詞", ph: "/hɑːrt/", zh: "<ruby>心<rt>ㄒㄧㄣ</rt></ruby>", ex: "Open my heart.（打開我的心）" },
      { en: "dream", type: "名詞", ph: "/driːm/", zh: "<ruby>夢<rt>ㄇㄥˋ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby>", ex: "My dream.（我的夢想）" },
      { en: "back", type: "副詞", ph: "/bæk/", zh: "<ruby>回<rt>ㄏㄨㄟˊ</rt></ruby><ruby>來<rt>ㄌㄞˊ</rt></ruby>", ex: "Come back.（回來）" },
      { en: "open", type: "動詞", ph: "/ˈoʊpən/", zh: "<ruby>打<rt>ㄉㄚˇ</rt></ruby><ruby>開<rt>ㄎㄞ</rt></ruby>", ex: "Open the door.（打開門）" },
      { en: "hope", type: "名詞", ph: "/hoʊp/", zh: "<ruby>希<rt>ㄒㄧ</rt></ruby><ruby>望<rt>ㄨㄤˋ</rt></ruby>", ex: "I hope so.（我希望如此）" },
      { en: "night", type: "名詞", ph: "/naɪt/", zh: "<ruby>夜<rt>ㄧㄝˋ</rt></ruby><ruby>晚<rt>ㄨㄢˇ</rt></ruby>", ex: "Good night.（晚安）" },
      { en: "again", type: "副詞", ph: "/əˈɡen/", zh: "<ruby>再<rt>ㄗㄞˋ</rt></ruby><ruby>一<rt>ㄧˊ</rt></ruby><ruby>次<rt>ㄘˋ</rt></ruby>", ex: "Try again.（再試一次）" },
      { en: "shadow", type: "名詞", ph: "/ˈʃædoʊ/", zh: "<ruby>影<rt>ㄧㄥˇ</rt></ruby><ruby>子<rt>˙ㄗ</rt></ruby>", ex: "My shadow.（我的影子）" },
      { en: "find", type: "動詞", ph: "/faɪnd/", zh: "<ruby>找<rt>ㄓㄠˇ</rt></ruby><ruby>到<rt>ㄉㄠˋ</rt></ruby>", ex: "Find a way.（找到一條路）" }
    ],
    advancedVocab: [
      { en: "lonely", type: "形容詞", ph: "/ˈloʊnli/", zh: "<ruby>寂<rt>ㄐㄧˊ</rt></ruby><ruby>寞<rt>ㄇㄛˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "I feel lonely.（我覺得寂寞）" },
      { en: "searching", type: "動詞", ph: "/ˈsɜːrtʃɪŋ/", zh: "<ruby>搜<rt>ㄙㄡ</rt></ruby><ruby>尋<rt>ㄒㄩㄣˊ</rt></ruby><ruby>中<rt>ㄓㄨㄥ</rt></ruby>", ex: "I'm searching for you.（我在找你）" },
      { en: "direction", type: "名詞", ph: "/dɪˈrekʃən/", zh: "<ruby>方<rt>ㄈㄤ</rt></ruby><ruby>向<rt>ㄒㄧㄤˋ</rt></ruby>", ex: "Which direction?（哪個方向？）" },
      { en: "inspiration", type: "名詞", ph: "/ˌɪnspəˈreɪʃən/", zh: "<ruby>靈<rt>ㄌㄧㄥˊ</rt></ruby><ruby>感<rt>ㄍㄢˇ</rt></ruby>", ex: "You are my inspiration.（你是我的靈感）" },
      { en: "moment", type: "名詞", ph: "/ˈmoʊmənt/", zh: "<ruby>時<rt>ㄕˊ</rt></ruby><ruby>刻<rt>ㄎㄜˋ</rt></ruby>", ex: "A special moment.（一個特別的時刻）" },
      { en: "trapped", type: "形容詞", ph: "/træpt/", zh: "<ruby>困<rt>ㄎㄨㄣˋ</rt></ruby><ruby>住<rt>ㄓㄨˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Trapped in the past.（困在過去）" },
      { en: "hiding", type: "動詞", ph: "/ˈhaɪdɪŋ/", zh: "<ruby>躲<rt>ㄉㄨㄛˇ</rt></ruby><ruby>藏<rt>ㄘㄤˊ</rt></ruby>", ex: "Hiding my feelings.（藏起感受）" },
      { en: "soul", type: "名詞", ph: "/soʊl/", zh: "<ruby>靈<rt>ㄌㄧㄥˊ</rt></ruby><ruby>魂<rt>ㄏㄨㄣˊ</rt></ruby>", ex: "Soul music.（靈魂樂）" }
    ],
    mission: "聽到 <b>love</b> 全家互相抱一下 🤗；聽到 <b>star</b> 雙手在頭上做閃亮星星 ✨；聽到 <b>way back into love</b> 副歌一起大聲跟唱！"
  },
  {
    slug: "lost-stars",
    owner: "南瓜爸爸",
    ownerColor: "#ff7a59",
    ownerAccent: "#cf4c3a",
    title: "Lost Stars",
    titleZh: "迷路的星星",
    titleZhRuby: "<ruby>迷<rt>ㄇㄧˊ</rt></ruby><ruby>路<rt>ㄌㄨˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>星<rt>ㄒㄧㄥ</rt></ruby><ruby>星<rt>˙ㄒㄧㄥ</rt></ruby>",
    artist: "Adam Levine",
    genre: "Folk Pop / Movie Ballad",
    year: "2013",
    album: "Begin Again 電影原聲帶",
    creator: "Gregg Alexander / Danielle Brisebois",
    cover: "assets/covers/Lost%20Stars.jpg",
    mp3: "assets/mp3/Lost%20Stars.mp3",
    lyricsDownload: "file:///Users/chennanhong/Desktop/AI%20%E8%82%B2%E5%85%92/%E8%8B%B1%E6%96%87%E6%AD%8C%E6%9B%B2/pumpkin_v3/02_%E6%AD%8C%E6%9B%B2%E5%AD%B8%E7%BF%92%E6%9C%AC/02_Lost_Stars.html",
    youtube: "https://www.youtube.com/watch?v=sLTRSakuugs",
    genreDesc: "<ruby>民<rt>ㄇㄧㄣˊ</rt></ruby><ruby>謠<rt>ㄧㄠˊ</rt></ruby><ruby>流<rt>ㄌㄧㄡˊ</rt></ruby><ruby>行<rt>ㄒㄧㄥˊ</rt></ruby>(Folk Pop)。<ruby>吉<rt>ㄐㄧˊ</rt></ruby><ruby>他<rt>˙ㄊㄚ</rt></ruby><ruby>輕<rt>ㄑㄧㄥ</rt></ruby><ruby>輕<rt>˙ㄑㄧㄥ</rt></ruby><ruby>刷<rt>ㄕㄨㄚ</rt></ruby>著<ruby>弦<rt>ㄒㄧㄢˊ</rt></ruby>，<ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>夜<rt>ㄧㄝˋ</rt></ruby><ruby>空<rt>ㄎㄨㄥ</rt></ruby><ruby>下<rt>ㄒㄧㄚˋ</rt></ruby><ruby>自<rt>ㄗˋ</rt></ruby><ruby>言<rt>ㄧㄢˊ</rt></ruby><ruby>自<rt>ㄗˋ</rt></ruby><ruby>語<rt>ㄩˇ</rt></ruby>。",
    meaning: "<ruby>歌<rt>ㄍㄜ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby><ruby>把<rt>ㄅㄚˇ</rt></ruby><ruby>人<rt>ㄖㄣˊ</rt></ruby><ruby>比<rt>ㄅㄧˇ</rt></ruby><ruby>喻<rt>ㄩˋ</rt></ruby><ruby>成<rt>ㄔㄥˊ</rt></ruby><ruby>星<rt>ㄒㄧㄥ</rt></ruby><ruby>星<rt>˙ㄒㄧㄥ</rt></ruby>。<ruby>就<rt>ㄐㄧㄡˋ</rt></ruby><ruby>算<rt>ㄙㄨㄢˋ</rt></ruby><ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>時<rt>ㄕˊ</rt></ruby><ruby>候<rt>˙ㄏㄡ</rt></ruby><ruby>會<rt>ㄏㄨㄟˋ</rt></ruby><ruby>迷<rt>ㄇㄧˊ</rt></ruby><ruby>路<rt>ㄌㄨˋ</rt></ruby>，<ruby>還<rt>ㄏㄞˊ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>可<rt>ㄎㄜˇ</rt></ruby><ruby>以<rt>ㄧˇ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>黑<rt>ㄏㄟ</rt></ruby><ruby>夜<rt>ㄧㄝˋ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby><ruby>慢<rt>ㄇㄢˋ</rt></ruby><ruby>慢<rt>˙ㄇㄢ</rt></ruby><ruby>發<rt>ㄈㄚ</rt></ruby><ruby>光<rt>ㄍㄨㄤ</rt></ruby>。",
    story: "這首歌把人比成星星。就算有時候會迷路，也還是可以在黑暗裡慢慢發光。",
    task: "全家一起在歌裡找『天空、星星、人生、希望』這幾類的字，找到就拍手一次。",
    practice: "We are not just lost. We can light up the dark. We can still shine.",
    celebrate: "星星模式啟動！這首是南瓜爸爸選的歌，我們一起在音樂裡找光亮。",
    keyLyrics: [
      { en: "Please don't see just a boy caught up in dreams.", zh: "<ruby>請<rt>ㄑㄧㄥˇ</rt></ruby><ruby>不<rt>ㄅㄨˊ</rt></ruby><ruby>要<rt>ㄧㄠˋ</rt></ruby><ruby>只<rt>ㄓˇ</rt></ruby><ruby>看<rt>ㄎㄢˋ</rt></ruby><ruby>到<rt>ㄉㄠˋ</rt></ruby><ruby>一<rt>ㄧˊ</rt></ruby><ruby>個<rt>˙ㄍㄜ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>做<rt>ㄗㄨㄛˋ</rt></ruby><ruby>夢<rt>ㄇㄥˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>男<rt>ㄋㄢˊ</rt></ruby><ruby>孩<rt>ㄏㄞˊ</rt></ruby>。" },
      { en: "I thought I saw you out there crying.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>以<rt>ㄧˇ</rt></ruby><ruby>為<rt>ㄨㄟˊ</rt></ruby><ruby>看<rt>ㄎㄢˋ</rt></ruby><ruby>見<rt>ㄐㄧㄢˋ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>遠<rt>ㄩㄢˇ</rt></ruby><ruby>方<rt>ㄈㄤ</rt></ruby><ruby>哭<rt>ㄎㄨ</rt></ruby><ruby>泣<rt>ㄑㄧˋ</rt></ruby>。" },
      { en: "Are we all lost stars trying to light up the dark?", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>們<rt>˙ㄇㄣ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>不<rt>ㄅㄨˊ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>都<rt>ㄉㄡ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>迷<rt>ㄇㄧˊ</rt></ruby><ruby>路<rt>ㄌㄨˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>星<rt>ㄒㄧㄥ</rt></ruby><ruby>星<rt>˙ㄒㄧㄥ</rt></ruby>，<ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>把<rt>ㄅㄚˇ</rt></ruby><ruby>黑<rt>ㄏㄟ</rt></ruby><ruby>夜<rt>ㄧㄝˋ</rt></ruby><ruby>點<rt>ㄉㄧㄢˇ</rt></ruby><ruby>亮<rt>ㄌㄧㄤˋ</rt></ruby>？" },
      { en: "God, give us the reason, youth is wasted on the young.", zh: "<ruby>神<rt>ㄕㄣˊ</rt></ruby><ruby>啊<rt>˙ㄚ</rt></ruby>，<ruby>給<rt>ㄍㄟˇ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>們<rt>˙ㄇㄣ</rt></ruby><ruby>一<rt>ㄧˊ</rt></ruby><ruby>個<rt>˙ㄍㄜ</rt></ruby><ruby>理<rt>ㄌㄧˇ</rt></ruby><ruby>由<rt>ㄧㄡˊ</rt></ruby>。" },
      { en: "Who are we? Just a speck of dust within the galaxy.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>們<rt>˙ㄇㄣ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>誰<rt>ㄕㄟˊ</rt></ruby>？<ruby>只<rt>ㄓˇ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>銀<rt>ㄧㄣˊ</rt></ruby><ruby>河<rt>ㄏㄜˊ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>粒<rt>ㄌㄧˋ</rt></ruby><ruby>小<rt>ㄒㄧㄠˇ</rt></ruby><ruby>小<rt>˙ㄒㄧㄠ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>灰<rt>ㄏㄨㄟ</rt></ruby><ruby>塵<rt>ㄔㄣˊ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "star", type: "名詞", ph: "/stɑːr/", zh: "<ruby>星<rt>ㄒㄧㄥ</rt></ruby><ruby>星<rt>˙ㄒㄧㄥ</rt></ruby>", ex: "Lost stars.（迷路的星星）" },
      { en: "light", type: "名詞", ph: "/laɪt/", zh: "<ruby>光<rt>ㄍㄨㄤ</rt></ruby>", ex: "Light up.（點亮）" },
      { en: "dark", type: "名詞", ph: "/dɑːrk/", zh: "<ruby>黑<rt>ㄏㄟ</rt></ruby><ruby>暗<rt>ㄢˋ</rt></ruby>", ex: "In the dark.（在黑暗中）" },
      { en: "sky", type: "名詞", ph: "/skaɪ/", zh: "<ruby>天<rt>ㄊㄧㄢ</rt></ruby><ruby>空<rt>ㄎㄨㄥ</rt></ruby>", ex: "Blue sky.（藍天）" },
      { en: "find", type: "動詞", ph: "/faɪnd/", zh: "<ruby>找<rt>ㄓㄠˇ</rt></ruby>", ex: "Find you.（找到你）" },
      { en: "lost", type: "形容詞", ph: "/lɔːst/", zh: "<ruby>迷<rt>ㄇㄧˊ</rt></ruby><ruby>路<rt>ㄌㄨˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "I'm lost.（我迷路了）" },
      { en: "shine", type: "動詞", ph: "/ʃaɪn/", zh: "<ruby>發<rt>ㄈㄚ</rt></ruby><ruby>光<rt>ㄍㄨㄤ</rt></ruby>", ex: "Stars shine.（星星發光）" },
      { en: "night", type: "名詞", ph: "/naɪt/", zh: "<ruby>夜<rt>ㄧㄝˋ</rt></ruby><ruby>晚<rt>ㄨㄢˇ</rt></ruby>", ex: "Dark night.（黑夜）" },
      { en: "dream", type: "名詞", ph: "/driːm/", zh: "<ruby>夢<rt>ㄇㄥˋ</rt></ruby>", ex: "Sweet dream.（甜夢）" },
      { en: "sing", type: "動詞", ph: "/sɪŋ/", zh: "<ruby>唱<rt>ㄔㄤˋ</rt></ruby><ruby>歌<rt>ㄍㄜ</rt></ruby>", ex: "Sing along.（一起唱）" },
      { en: "young", type: "形容詞", ph: "/jʌŋ/", zh: "<ruby>年<rt>ㄋㄧㄢˊ</rt></ruby><ruby>輕<rt>ㄑㄧㄥ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Young heart.（年輕的心）" },
      { en: "free", type: "形容詞", ph: "/friː/", zh: "<ruby>自<rt>ㄗˋ</rt></ruby><ruby>由<rt>ㄧㄡˊ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Feel free.（感到自由）" }
    ],
    advancedVocab: [
      { en: "galaxy", type: "名詞", ph: "/ˈɡæləksi/", zh: "<ruby>銀<rt>ㄧㄣˊ</rt></ruby><ruby>河<rt>ㄏㄜˊ</rt></ruby>", ex: "Our galaxy.（我們的銀河）" },
      { en: "fantasies", type: "名詞", ph: "/ˈfæntəsiz/", zh: "<ruby>幻<rt>ㄏㄨㄢˋ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby>", ex: "Sweet fantasies.（甜美的幻想）" },
      { en: "searching", type: "動詞", ph: "/ˈsɜːrtʃɪŋ/", zh: "<ruby>尋<rt>ㄒㄩㄣˊ</rt></ruby><ruby>找<rt>ㄓㄠˇ</rt></ruby>", ex: "Searching for light.（尋找光）" },
      { en: "meaning", type: "名詞", ph: "/ˈmiːnɪŋ/", zh: "<ruby>意<rt>ㄧˋ</rt></ruby><ruby>義<rt>ㄧˋ</rt></ruby>", ex: "Find meaning.（找到意義）" },
      { en: "reality", type: "名詞", ph: "/riˈæləti/", zh: "<ruby>現<rt>ㄒㄧㄢˋ</rt></ruby><ruby>實<rt>ㄕˊ</rt></ruby>", ex: "Harsh reality.（殘酷現實）" },
      { en: "youth", type: "名詞", ph: "/juːθ/", zh: "<ruby>青<rt>ㄑㄧㄥ</rt></ruby><ruby>春<rt>ㄔㄨㄣ</rt></ruby>", ex: "My youth.（我的青春）" },
      { en: "sorrow", type: "名詞", ph: "/ˈsɑːroʊ/", zh: "<ruby>悲<rt>ㄅㄟ</rt></ruby><ruby>傷<rt>ㄕㄤ</rt></ruby>", ex: "Deep sorrow.（深深的悲傷）" },
      { en: "careful", type: "形容詞", ph: "/ˈkerfəl/", zh: "<ruby>小<rt>ㄒㄧㄠˇ</rt></ruby><ruby>心<rt>ㄒㄧㄣ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Be careful.（小心）" }
    ],
    mission: "聽到 <b>star</b> 雙手舉高做星星 ⭐；聽到 <b>dark</b> 把手蓋在眼睛上 🌙；唱到 <b>lost stars</b> 一家人手牽手一起搖擺。"
  },
  {
    slug: "make-you-mine",
    owner: "南瓜爸爸",
    ownerColor: "#ff7a59",
    ownerAccent: "#cf4c3a",
    title: "Make You Mine",
    titleZh: "讓你成為我的",
    titleZhRuby: "<ruby>讓<rt>ㄖㄤˋ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>成<rt>ㄔㄥˊ</rt></ruby><ruby>為<rt>ㄨㄟˊ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>",
    artist: "PUBLIC",
    genre: "Pop Rock",
    year: "2018",
    album: "Let's Remember Sundays",
    creator: "John Vaughn / Ben Lapps / Matthew Alvarado",
    cover: "assets/covers/Make%20You%20Mine.jpg",
    mp3: "assets/mp3/Make%20You%20Mine.mp3",
    lyricsDownload: "file:///Users/chennanhong/Desktop/AI%20%E8%82%B2%E5%85%92/%E8%8B%B1%E6%96%87%E6%AD%8C%E6%9B%B2/pumpkin_v3/02_%E6%AD%8C%E6%9B%B2%E5%AD%B8%E7%BF%92%E6%9C%AC/03_Make_You_Mine.html",
    youtube: "https://www.youtube.com/watch?v=nLnp0tpZ0ok",
    genreDesc: "<ruby>流<rt>ㄌㄧㄡˊ</rt></ruby><ruby>行<rt>ㄒㄧㄥˊ</rt></ruby><ruby>搖<rt>ㄧㄠˊ</rt></ruby><ruby>滾<rt>ㄍㄨㄣˇ</rt></ruby>(Pop Rock)。<ruby>節<rt>ㄐㄧㄝˊ</rt></ruby><ruby>奏<rt>ㄗㄡˋ</rt></ruby><ruby>明<rt>ㄇㄧㄥˊ</rt></ruby><ruby>快<rt>ㄎㄨㄞˋ</rt></ruby>，<ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>適<rt>ㄕˋ</rt></ruby><ruby>合<rt>ㄏㄜˊ</rt></ruby><ruby>全<rt>ㄑㄩㄢˊ</rt></ruby><ruby>家<rt>ㄐㄧㄚ</rt></ruby><ruby>拍<rt>ㄆㄞ</rt></ruby><ruby>手<rt>ㄕㄡˇ</rt></ruby>。",
    meaning: "<ruby>這<rt>ㄓㄜˋ</rt></ruby><ruby>首<rt>ㄕㄡˇ</rt></ruby><ruby>歌<rt>ㄍㄜ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>說<rt>ㄕㄨㄛ</rt></ruby>：「<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>和<rt>ㄏㄢˋ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>更<rt>ㄍㄥˋ</rt></ruby><ruby>靠<rt>ㄎㄠˋ</rt></ruby><ruby>近<rt>ㄐㄧㄣˋ</rt></ruby>、<ruby>慢<rt>ㄇㄢˋ</rt></ruby><ruby>慢<rt>˙ㄇㄢ</rt></ruby><ruby>牽<rt>ㄑㄧㄢ</rt></ruby><ruby>手<rt>ㄕㄡˇ</rt></ruby>」。<ruby>給<rt>ㄍㄟˇ</rt></ruby><ruby>小<rt>ㄒㄧㄠˇ</rt></ruby><ruby>朋<rt>ㄆㄥˊ</rt></ruby><ruby>友<rt>ㄧㄡˇ</rt></ruby><ruby>就<rt>ㄐㄧㄡˋ</rt></ruby><ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>說<rt>ㄕㄨㄛ</rt></ruby><ruby>珍<rt>ㄓㄣ</rt></ruby><ruby>惜<rt>ㄒㄧˊ</rt></ruby><ruby>家<rt>ㄐㄧㄚ</rt></ruby><ruby>人<rt>ㄖㄣˊ</rt></ruby>。",
    story: "這首歌很有往前衝的感覺，像在說想和喜歡的人更靠近。對孩子來說，可以想成珍惜家人和朋友。",
    task: "先聽一次副歌，再找出歌裡和『關係』『感受』『慢慢來』有關的字。",
    practice: "Take it slow. Put your hand in mine. I do not want to let go.",
    celebrate: "歡呼聲送給南瓜爸爸！這首歌很有衝勁，很適合一家人一起唱。",
    keyLyrics: [
      { en: "I don't mind if we take some time.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>不<rt>ㄅㄨˊ</rt></ruby><ruby>介<rt>ㄐㄧㄝˋ</rt></ruby><ruby>意<rt>ㄧˋ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>們<rt>˙ㄇㄣ</rt></ruby><ruby>花<rt>ㄏㄨㄚ</rt></ruby><ruby>一<rt>ㄧ</rt></ruby><ruby>點<rt>ㄉㄧㄢˇ</rt></ruby><ruby>時<rt>ㄕˊ</rt></ruby><ruby>間<rt>ㄐㄧㄢ</rt></ruby>。" },
      { en: "Put your hand in mine and take it slow.", zh: "<ruby>把<rt>ㄅㄚˇ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>手<rt>ㄕㄡˇ</rt></ruby><ruby>放<rt>ㄈㄤˋ</rt></ruby><ruby>進<rt>ㄐㄧㄣˋ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>手<rt>ㄕㄡˇ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby>，<ruby>慢<rt>ㄇㄢˋ</rt></ruby><ruby>慢<rt>˙ㄇㄢ</rt></ruby><ruby>來<rt>ㄌㄞˊ</rt></ruby>。" },
      { en: "I just wanna make you mine.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>只<rt>ㄓˇ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>讓<rt>ㄖㄤˋ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>成<rt>ㄔㄥˊ</rt></ruby><ruby>為<rt>ㄨㄟˊ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>。" },
      { en: "It's okay if you take your time.", zh: "<ruby>慢<rt>ㄇㄢˋ</rt></ruby><ruby>慢<rt>˙ㄇㄢ</rt></ruby><ruby>來<rt>ㄌㄞˊ</rt></ruby><ruby>沒<rt>ㄇㄟˊ</rt></ruby><ruby>關<rt>ㄍㄨㄢ</rt></ruby><ruby>係<rt>˙ㄒㄧ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "mine", type: "代名詞", ph: "/maɪn/", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "It's mine.（這是我的）" },
      { en: "hand", type: "名詞", ph: "/hænd/", zh: "<ruby>手<rt>ㄕㄡˇ</rt></ruby>", ex: "Your hand.（你的手）" },
      { en: "hold", type: "動詞", ph: "/hoʊld/", zh: "<ruby>握<rt>ㄨㄛˋ</rt></ruby><ruby>住<rt>ㄓㄨˋ</rt></ruby>", ex: "Hold on.（撐住）" },
      { en: "slow", type: "形容詞", ph: "/sloʊ/", zh: "<ruby>慢<rt>ㄇㄢˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Take it slow.（慢慢來）" },
      { en: "time", type: "名詞", ph: "/taɪm/", zh: "<ruby>時<rt>ㄕˊ</rt></ruby><ruby>間<rt>ㄐㄧㄢ</rt></ruby>", ex: "Take time.（花時間）" },
      { en: "walk", type: "動詞", ph: "/wɔːk/", zh: "<ruby>散<rt>ㄙㄢˋ</rt></ruby><ruby>步<rt>ㄅㄨˋ</rt></ruby>", ex: "Let's walk.（我們散步）" },
      { en: "home", type: "名詞", ph: "/hoʊm/", zh: "<ruby>家<rt>ㄐㄧㄚ</rt></ruby>", ex: "Go home.（回家）" },
      { en: "stay", type: "動詞", ph: "/steɪ/", zh: "<ruby>停<rt>ㄊㄧㄥˊ</rt></ruby><ruby>留<rt>ㄌㄧㄡˊ</rt></ruby>", ex: "Stay here.（待在這裡）" },
      { en: "love", type: "名詞", ph: "/lʌv/", zh: "<ruby>愛<rt>ㄞˋ</rt></ruby>", ex: "Big love.（大大的愛）" },
      { en: "sure", type: "形容詞", ph: "/ʃʊr/", zh: "<ruby>確<rt>ㄑㄩㄝˋ</rt></ruby><ruby>定<rt>ㄉㄧㄥˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "I'm sure.（我很確定）" },
      { en: "kiss", type: "動詞", ph: "/kɪs/", zh: "<ruby>親<rt>ㄑㄧㄣ</rt></ruby><ruby>吻<rt>ㄨㄣˇ</rt></ruby>", ex: "A sweet kiss.（甜甜的吻）" },
      { en: "smile", type: "名詞", ph: "/smaɪl/", zh: "<ruby>微<rt>ㄨㄟˊ</rt></ruby><ruby>笑<rt>ㄒㄧㄠˋ</rt></ruby>", ex: "Your smile.（你的微笑）" }
    ],
    advancedVocab: [
      { en: "darlin'", type: "名詞", ph: "/ˈdɑːrlɪn/", zh: "<ruby>親<rt>ㄑㄧㄣ</rt></ruby><ruby>愛<rt>ㄞˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Hi, darlin'.（嗨，親愛的）" },
      { en: "slipping", type: "動詞", ph: "/ˈslɪpɪŋ/", zh: "<ruby>溜<rt>ㄌㄧㄡ</rt></ruby><ruby>走<rt>ㄗㄡˇ</rt></ruby>", ex: "Time slipping.（時間溜走）" },
      { en: "fingers", type: "名詞", ph: "/ˈfɪŋɡərz/", zh: "<ruby>手<rt>ㄕㄡˇ</rt></ruby><ruby>指<rt>ㄓˇ</rt></ruby>", ex: "Ten fingers.（十根手指）" },
      { en: "numb", type: "形容詞", ph: "/nʌm/", zh: "<ruby>麻<rt>ㄇㄚˊ</rt></ruby><ruby>木<rt>ㄇㄨˋ</rt></ruby>", ex: "Feel numb.（感到麻木）" },
      { en: "suppose", type: "動詞", ph: "/səˈpoʊz/", zh: "<ruby>應<rt>ㄧㄥ</rt></ruby><ruby>該<rt>ㄍㄞ</rt></ruby>", ex: "Suppose to.（應該要）" },
      { en: "mess", type: "名詞", ph: "/mes/", zh: "<ruby>混<rt>ㄏㄨㄣˋ</rt></ruby><ruby>亂<rt>ㄌㄨㄢˋ</rt></ruby>", ex: "Big mess.（一團亂）" },
      { en: "anyway", type: "副詞", ph: "/ˈeniweɪ/", zh: "<ruby>總<rt>ㄗㄨㄥˇ</rt></ruby><ruby>之<rt>ㄓ</rt></ruby>", ex: "Anyway, it's fine.（總之沒事）" },
      { en: "miss", type: "動詞", ph: "/mɪs/", zh: "<ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>念<rt>ㄋㄧㄢˋ</rt></ruby>", ex: "Miss you.（想你）" }
    ],
    mission: "聽到 <b>mine</b> 雙手放在胸口 🫶；聽到 <b>slow</b> 全家動作慢動作；副歌 <b>make you mine</b> 一起左右搖擺。"
  },
  {
    slug: "lemon-tree",
    owner: "Ann 媽媽",
    ownerColor: "#2a9d8f",
    ownerAccent: "#1f6f66",
    title: "Lemon Tree",
    titleZh: "檸檬樹",
    titleZhRuby: "<ruby>檸<rt>ㄋㄧㄥˊ</rt></ruby><ruby>檬<rt>ㄇㄥˊ</rt></ruby><ruby>樹<rt>ㄕㄨˋ</rt></ruby>",
    artist: "Fool's Garden",
    genre: "Pop Rock",
    year: "1995",
    album: "Dish of the Day",
    creator: "Peter Freudenthaler",
    cover: "assets/covers/Lemon%20Tree.jpg",
    mp3: "assets/mp3/Lemon%20Tree.mp3",
    lyricsDownload: "file:///Users/chennanhong/Desktop/AI%20%E8%82%B2%E5%85%92/%E8%8B%B1%E6%96%87%E6%AD%8C%E6%9B%B2/pumpkin_v3/02_%E6%AD%8C%E6%9B%B2%E5%AD%B8%E7%BF%92%E6%9C%AC/04_Lemon_Tree.html",
    youtube: "https://www.youtube.com/watch?v=wCQfkEkePx8",
    genreDesc: "<ruby>輕<rt>ㄑㄧㄥ</rt></ruby><ruby>快<rt>ㄎㄨㄞˋ</rt></ruby><ruby>流<rt>ㄌㄧㄡˊ</rt></ruby><ruby>行<rt>ㄒㄧㄥˊ</rt></ruby><ruby>搖<rt>ㄧㄠˊ</rt></ruby><ruby>滾<rt>ㄍㄨㄣˇ</rt></ruby>。<ruby>旋<rt>ㄒㄩㄢˊ</rt></ruby><ruby>律<rt>ㄌㄩˋ</rt></ruby><ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>好<rt>ㄏㄠˇ</rt></ruby><ruby>記<rt>ㄐㄧˋ</rt></ruby>，<ruby>小<rt>ㄒㄧㄠˇ</rt></ruby><ruby>朋<rt>ㄆㄥˊ</rt></ruby><ruby>友<rt>ㄧㄡˇ</rt></ruby><ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>容<rt>ㄖㄨㄥˊ</rt></ruby><ruby>易<rt>ㄧˋ</rt></ruby><ruby>跟<rt>ㄍㄣ</rt></ruby><ruby>著<rt>˙ㄓㄜ</rt></ruby><ruby>唱<rt>ㄔㄤˋ</rt></ruby>。",
    meaning: "<ruby>下<rt>ㄒㄧㄚˋ</rt></ruby><ruby>著<rt>˙ㄓㄜ</rt></ruby><ruby>小<rt>ㄒㄧㄠˇ</rt></ruby><ruby>雨<rt>ㄩˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>午<rt>ㄨˇ</rt></ruby><ruby>後<rt>ㄏㄡˋ</rt></ruby>，<ruby>主<rt>ㄓㄨˇ</rt></ruby><ruby>角<rt>ㄐㄩㄝˊ</rt></ruby><ruby>坐<rt>ㄗㄨㄛˋ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>窗<rt>ㄔㄨㄤ</rt></ruby><ruby>前<rt>ㄑㄧㄢˊ</rt></ruby>，<ruby>心<rt>ㄒㄧㄣ</rt></ruby><ruby>情<rt>ㄑㄧㄥˊ</rt></ruby><ruby>悶<rt>ㄇㄣˋ</rt></ruby><ruby>悶<rt>˙ㄇㄣ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>。<ruby>可<rt>ㄎㄜˇ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>窗<rt>ㄔㄨㄤ</rt></ruby><ruby>外<rt>ㄨㄞˋ</rt></ruby><ruby>還<rt>ㄏㄞˊ</rt></ruby><ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>棵<rt>ㄎㄜ</rt></ruby><ruby>檸<rt>ㄋㄧㄥˊ</rt></ruby><ruby>檬<rt>ㄇㄥˊ</rt></ruby><ruby>樹<rt>ㄕㄨˋ</rt></ruby><ruby>陪<rt>ㄆㄟˊ</rt></ruby><ruby>著<rt>˙ㄓㄜ</rt></ruby><ruby>他<rt>ㄊㄚ</rt></ruby>。",
    story: "旋律很輕快，可是心情有一點悶悶的。很適合陪孩子認識不同的感受。",
    task: "一邊聽一邊找歌裡和『時間』『天氣』『感受』有關的單字。",
    practice: "It is a rainy afternoon. I wonder why. I want to change my point of view.",
    celebrate: "Ann 媽媽的歌登場了！檸檬樹搖一搖，今天一起邊唱邊轉圈圈。",
    keyLyrics: [
      { en: "I'm sitting here in a boring room.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>坐<rt>ㄗㄨㄛˋ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>間<rt>ㄐㄧㄢ</rt></ruby><ruby>好<rt>ㄏㄠˇ</rt></ruby><ruby>無<rt>ㄨˊ</rt></ruby><ruby>聊<rt>ㄌㄧㄠˊ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>房<rt>ㄈㄤˊ</rt></ruby><ruby>間<rt>ㄐㄧㄢ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby>。" },
      { en: "It's just another rainy Sunday afternoon.", zh: "<ruby>又<rt>ㄧㄡˋ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>一<rt>ㄧˊ</rt></ruby><ruby>個<rt>˙ㄍㄜ</rt></ruby><ruby>下<rt>ㄒㄧㄚˋ</rt></ruby><ruby>雨<rt>ㄩˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>星<rt>ㄒㄧㄥ</rt></ruby><ruby>期<rt>ㄑㄧˊ</rt></ruby><ruby>天<rt>ㄊㄧㄢ</rt></ruby><ruby>下<rt>ㄒㄧㄚˋ</rt></ruby><ruby>午<rt>ㄨˇ</rt></ruby>。" },
      { en: "I wonder how, I wonder why.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>著<rt>˙ㄓㄜ</rt></ruby><ruby>怎<rt>ㄗㄣˇ</rt></ruby><ruby>麼<rt>˙ㄇㄜ</rt></ruby><ruby>會<rt>ㄏㄨㄟˋ</rt></ruby>，<ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>著<rt>˙ㄓㄜ</rt></ruby><ruby>為<rt>ㄨㄟˋ</rt></ruby><ruby>什<rt>ㄕㄜˊ</rt></ruby><ruby>麼<rt>˙ㄇㄜ</rt></ruby>。" },
      { en: "And all that I can see is just a yellow lemon tree.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>只<rt>ㄓˇ</rt></ruby><ruby>看<rt>ㄎㄢˋ</rt></ruby><ruby>得<rt>˙ㄉㄜ</rt></ruby><ruby>到<rt>ㄉㄠˋ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>棵<rt>ㄎㄜ</rt></ruby><ruby>黃<rt>ㄏㄨㄤˊ</rt></ruby><ruby>色<rt>ㄙㄜˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>檸<rt>ㄋㄧㄥˊ</rt></ruby><ruby>檬<rt>ㄇㄥˊ</rt></ruby><ruby>樹<rt>ㄕㄨˋ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "rain", type: "名詞", ph: "/reɪn/", zh: "<ruby>雨<rt>ㄩˇ</rt></ruby>", ex: "Heavy rain.（大雨）" },
      { en: "sun", type: "名詞", ph: "/sʌn/", zh: "<ruby>太<rt>ㄊㄞˋ</rt></ruby><ruby>陽<rt>ㄧㄤˊ</rt></ruby>", ex: "The sun.（太陽）" },
      { en: "tree", type: "名詞", ph: "/triː/", zh: "<ruby>樹<rt>ㄕㄨˋ</rt></ruby>", ex: "A big tree.（一棵大樹）" },
      { en: "yellow", type: "形容詞", ph: "/ˈjeloʊ/", zh: "<ruby>黃<rt>ㄏㄨㄤˊ</rt></ruby><ruby>色<rt>ㄙㄜˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Yellow hat.（黃帽子）" },
      { en: "room", type: "名詞", ph: "/ruːm/", zh: "<ruby>房<rt>ㄈㄤˊ</rt></ruby><ruby>間<rt>ㄐㄧㄢ</rt></ruby>", ex: "My room.（我的房間）" },
      { en: "window", type: "名詞", ph: "/ˈwɪndoʊ/", zh: "<ruby>窗<rt>ㄔㄨㄤ</rt></ruby><ruby>戶<rt>ㄏㄨˋ</rt></ruby>", ex: "Open window.（打開的窗戶）" },
      { en: "afternoon", type: "名詞", ph: "/ˌæftərˈnuːn/", zh: "<ruby>下<rt>ㄒㄧㄚˋ</rt></ruby><ruby>午<rt>ㄨˇ</rt></ruby>", ex: "Good afternoon.（午安）" },
      { en: "cloud", type: "名詞", ph: "/klaʊd/", zh: "<ruby>雲<rt>ㄩㄣˊ</rt></ruby>", ex: "Big cloud.（大雲）" },
      { en: "head", type: "名詞", ph: "/hed/", zh: "<ruby>頭<rt>ㄊㄡˊ</rt></ruby>", ex: "My head.（我的頭）" },
      { en: "waiting", type: "動詞", ph: "/ˈweɪtɪŋ/", zh: "<ruby>等<rt>ㄉㄥˇ</rt></ruby><ruby>待<rt>ㄉㄞˋ</rt></ruby>", ex: "Still waiting.（還在等）" },
      { en: "blue", type: "形容詞", ph: "/bluː/", zh: "<ruby>藍<rt>ㄌㄢˊ</rt></ruby><ruby>色<rt>ㄙㄜˋ</rt></ruby>", ex: "Feel blue.（心情低落）" },
      { en: "turn", type: "動詞", ph: "/tɜːrn/", zh: "<ruby>轉<rt>ㄓㄨㄢˇ</rt></ruby><ruby>動<rt>ㄉㄨㄥˋ</rt></ruby>", ex: "Turn around.（轉過來）" }
    ],
    advancedVocab: [
      { en: "boring", type: "形容詞", ph: "/ˈbɔːrɪŋ/", zh: "<ruby>無<rt>ㄨˊ</rt></ruby><ruby>聊<rt>ㄌㄧㄠˊ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "So boring.（好無聊）" },
      { en: "wonder", type: "動詞", ph: "/ˈwʌndər/", zh: "<ruby>納<rt>ㄋㄚˋ</rt></ruby><ruby>悶<rt>ㄇㄣˋ</rt></ruby>", ex: "I wonder why.（我納悶為什麼）" },
      { en: "lonely", type: "形容詞", ph: "/ˈloʊnli/", zh: "<ruby>孤<rt>ㄍㄨ</rt></ruby><ruby>單<rt>ㄉㄢ</rt></ruby>", ex: "Feel lonely.（感到孤單）" },
      { en: "perspective", type: "名詞", ph: "/pərˈspektɪv/", zh: "<ruby>觀<rt>ㄍㄨㄢ</rt></ruby><ruby>點<rt>ㄉㄧㄢˇ</rt></ruby>", ex: "A new perspective.（新的觀點）" },
      { en: "isolation", type: "名詞", ph: "/ˌaɪsəˈleɪʃn/", zh: "<ruby>孤<rt>ㄍㄨ</rt></ruby><ruby>立<rt>ㄌㄧˋ</rt></ruby>", ex: "In isolation.（在孤立中）" },
      { en: "desert", type: "名詞", ph: "/ˈdezərt/", zh: "<ruby>沙<rt>ㄕㄚ</rt></ruby><ruby>漠<rt>ㄇㄛˋ</rt></ruby>", ex: "Big desert.（大沙漠）" },
      { en: "anyhow", type: "副詞", ph: "/ˈenihaʊ/", zh: "<ruby>無<rt>ㄨˊ</rt></ruby><ruby>論<rt>ㄌㄨㄣˋ</rt></ruby><ruby>如<rt>ㄖㄨˊ</rt></ruby><ruby>何<rt>ㄏㄜˊ</rt></ruby>", ex: "Anyhow, let's go.（總之我們走）" },
      { en: "shower", type: "名詞", ph: "/ˈʃaʊər/", zh: "<ruby>陣<rt>ㄓㄣˋ</rt></ruby><ruby>雨<rt>ㄩˇ</rt></ruby>", ex: "A rain shower.（一陣雨）" }
    ],
    mission: "聽到 <b>rain</b> 雙手手指像下雨 🌧️；聽到 <b>yellow</b> 找身上的黃色物品；副歌 <b>lemon tree</b> 和全家一起轉圈圈。"
  },
  {
    slug: "something-just-like-this",
    owner: "Ann 媽媽",
    ownerColor: "#2a9d8f",
    ownerAccent: "#1f6f66",
    title: "Something Just Like This",
    titleZh: "就像這樣的事",
    titleZhRuby: "<ruby>就<rt>ㄐㄧㄡˋ</rt></ruby><ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>這<rt>ㄓㄜˋ</rt></ruby><ruby>樣<rt>ㄧㄤˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>事<rt>ㄕˋ</rt></ruby>",
    artist: "The Chainsmokers & Coldplay",
    genre: "EDM Pop",
    year: "2017",
    album: "Memories...Do Not Open",
    creator: "Chris Martin / Andrew Taggart",
    cover: "assets/covers/Something%20Just%20Like%20This.jpg",
    mp3: "assets/mp3/Something%20Just%20Like%20This.mp3",
    lyricsDownload: "",
    youtube: "https://www.youtube.com/watch?v=FM7MFYoylVs",
    genreDesc: "<ruby>電<rt>ㄉㄧㄢˋ</rt></ruby><ruby>子<rt>˙ㄗ</rt></ruby><ruby>流<rt>ㄌㄧㄡˊ</rt></ruby><ruby>行<rt>ㄒㄧㄥˊ</rt></ruby>(EDM Pop)。<ruby>節<rt>ㄐㄧㄝˊ</rt></ruby><ruby>奏<rt>ㄗㄡˋ</rt></ruby><ruby>感<rt>ㄍㄢˇ</rt></ruby><ruby>強<rt>ㄑㄧㄤˊ</rt></ruby>，<ruby>副<rt>ㄈㄨˋ</rt></ruby><ruby>歌<rt>ㄍㄜ</rt></ruby><ruby>超<rt>ㄔㄠ</rt></ruby><ruby>級<rt>ㄐㄧˊ</rt></ruby><ruby>好<rt>ㄏㄠˇ</rt></ruby><ruby>跟<rt>ㄍㄣ</rt></ruby>。",
    meaning: "<ruby>主<rt>ㄓㄨˇ</rt></ruby><ruby>角<rt>ㄐㄩㄝˊ</rt></ruby><ruby>說<rt>ㄕㄨㄛ</rt></ruby>：<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>不<rt>ㄅㄨˊ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>超<rt>ㄔㄠ</rt></ruby><ruby>人<rt>ㄖㄣˊ</rt></ruby>，<ruby>也<rt>ㄧㄝˇ</rt></ruby><ruby>不<rt>ㄅㄨˋ</rt></ruby><ruby>用<rt>ㄩㄥˋ</rt></ruby><ruby>當<rt>ㄉㄤ</rt></ruby><ruby>英<rt>ㄧㄥ</rt></ruby><ruby>雄<rt>ㄒㄩㄥˊ</rt></ruby>。<ruby>真<rt>ㄓㄣ</rt></ruby><ruby>正<rt>ㄓㄥˋ</rt></ruby><ruby>重<rt>ㄓㄨㄥˋ</rt></ruby><ruby>要<rt>ㄧㄠˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby>，<ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>人<rt>ㄖㄣˊ</rt></ruby><ruby>陪<rt>ㄆㄟˊ</rt></ruby><ruby>伴<rt>ㄅㄢˋ</rt></ruby>、<ruby>懂<rt>ㄉㄨㄥˇ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby>。",
    story: "這首歌在說：真正重要的，不一定是超級能力，而是有人陪伴你、懂你。",
    task: "先聽一次主歌，找出英雄、神話、故事書裡會出現的字。",
    practice: "I am not looking for superhuman gifts. I want something just like this.",
    celebrate: "超級英雄集合！這首是 Ann 媽媽選的歌，準備一起大聲唱副歌。",
    keyLyrics: [
      { en: "I've been reading books of old.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>直<rt>ㄓˊ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>讀<rt>ㄉㄨˊ</rt></ruby><ruby>古<rt>ㄍㄨˇ</rt></ruby><ruby>老<rt>ㄌㄠˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>書<rt>ㄕㄨ</rt></ruby>。" },
      { en: "She said, where'd you wanna go?", zh: "<ruby>她<rt>ㄊㄚ</rt></ruby><ruby>說<rt>ㄕㄨㄛ</rt></ruby>：<ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>去<rt>ㄑㄩˋ</rt></ruby><ruby>哪<rt>ㄋㄚˇ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby>？" },
      { en: "I'm not looking for somebody with some superhuman gifts.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>不<rt>ㄅㄨˊ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>找<rt>ㄓㄠˇ</rt></ruby><ruby>一<rt>ㄧˊ</rt></ruby><ruby>個<rt>˙ㄍㄜ</rt></ruby><ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>超<rt>ㄔㄠ</rt></ruby><ruby>能<rt>ㄋㄥˊ</rt></ruby><ruby>力<rt>ㄌㄧˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>人<rt>ㄖㄣˊ</rt></ruby>。" },
      { en: "I want something just like this.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>要<rt>ㄧㄠˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>，<ruby>就<rt>ㄐㄧㄡˋ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby><ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>這<rt>ㄓㄜˋ</rt></ruby><ruby>樣<rt>ㄧㄤˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>事<rt>ㄕˋ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "hero", type: "名詞", ph: "/ˈhɪroʊ/", zh: "<ruby>英<rt>ㄧㄥ</rt></ruby><ruby>雄<rt>ㄒㄩㄥˊ</rt></ruby>", ex: "My hero.（我的英雄）" },
      { en: "story", type: "名詞", ph: "/ˈstɔːri/", zh: "<ruby>故<rt>ㄍㄨˋ</rt></ruby><ruby>事<rt>ㄕˋ</rt></ruby>", ex: "A short story.（短故事）" },
      { en: "book", type: "名詞", ph: "/bʊk/", zh: "<ruby>書<rt>ㄕㄨ</rt></ruby>", ex: "Read a book.（讀書）" },
      { en: "power", type: "名詞", ph: "/ˈpaʊər/", zh: "<ruby>力<rt>ㄌㄧˋ</rt></ruby><ruby>量<rt>ㄌㄧㄤˋ</rt></ruby>", ex: "Super power.（超能力）" },
      { en: "gift", type: "名詞", ph: "/ɡɪft/", zh: "<ruby>禮<rt>ㄌㄧˇ</rt></ruby><ruby>物<rt>ㄨˋ</rt></ruby>", ex: "A gift for you.（給你的禮物）" },
      { en: "simple", type: "形容詞", ph: "/ˈsɪmpl/", zh: "<ruby>簡<rt>ㄐㄧㄢˇ</rt></ruby><ruby>單<rt>ㄉㄢ</rt></ruby>", ex: "So simple.（好簡單）" },
      { en: "hand", type: "名詞", ph: "/hænd/", zh: "<ruby>手<rt>ㄕㄡˇ</rt></ruby>", ex: "Hold my hand.（握我的手）" },
      { en: "kiss", type: "動詞", ph: "/kɪs/", zh: "<ruby>親<rt>ㄑㄧㄣ</rt></ruby><ruby>吻<rt>ㄨㄣˇ</rt></ruby>", ex: "Good night kiss.（晚安吻）" },
      { en: "moon", type: "名詞", ph: "/muːn/", zh: "<ruby>月<rt>ㄩㄝˋ</rt></ruby><ruby>亮<rt>ㄌㄧㄤˋ</rt></ruby>", ex: "Full moon.（滿月）" },
      { en: "special", type: "形容詞", ph: "/ˈspeʃl/", zh: "<ruby>特<rt>ㄊㄜˋ</rt></ruby><ruby>別<rt>ㄅㄧㄝˊ</rt></ruby>", ex: "Very special.（很特別）" },
      { en: "close", type: "形容詞", ph: "/kloʊs/", zh: "<ruby>靠<rt>ㄎㄠˋ</rt></ruby><ruby>近<rt>ㄐㄧㄣˋ</rt></ruby>", ex: "Come close.（靠近一點）" },
      { en: "just", type: "副詞", ph: "/dʒʌst/", zh: "<ruby>只<rt>ㄓˇ</rt></ruby><ruby>是<rt>ㄕˋ</rt></ruby>", ex: "Just like this.（就像這樣）" }
    ],
    advancedVocab: [
      { en: "legends", type: "名詞", ph: "/ˈledʒəndz/", zh: "<ruby>傳<rt>ㄔㄨㄢˊ</rt></ruby><ruby>說<rt>ㄕㄨㄛ</rt></ruby>", ex: "Old legends.（古老的傳說）" },
      { en: "myths", type: "名詞", ph: "/mɪθs/", zh: "<ruby>神<rt>ㄕㄣˊ</rt></ruby><ruby>話<rt>ㄏㄨㄚˋ</rt></ruby>", ex: "Greek myths.（希臘神話）" },
      { en: "Achilles", type: "專有名詞", ph: "/əˈkɪliːz/", zh: "<ruby>阿<rt>ㄚ</rt></ruby><ruby>基<rt>ㄐㄧ</rt></ruby><ruby>里<rt>ㄌㄧˇ</rt></ruby><ruby>斯<rt>˙ㄙ</rt></ruby>", ex: "Brave Achilles.（勇敢的阿基里斯）" },
      { en: "superhuman", type: "形容詞", ph: "/ˌsuːpərˈhjuːmən/", zh: "<ruby>超<rt>ㄔㄠ</rt></ruby><ruby>人<rt>ㄖㄣˊ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Superhuman gifts.（超能力）" },
      { en: "fairytale", type: "名詞", ph: "/ˈferiteɪl/", zh: "<ruby>童<rt>ㄊㄨㄥˊ</rt></ruby><ruby>話<rt>ㄏㄨㄚˋ</rt></ruby>", ex: "Fairytale ending.（童話結局）" },
      { en: "bliss", type: "名詞", ph: "/blɪs/", zh: "<ruby>幸<rt>ㄒㄧㄥˋ</rt></ruby><ruby>福<rt>ㄈㄨˊ</rt></ruby>", ex: "Pure bliss.（純粹的幸福）" },
      { en: "clearly", type: "副詞", ph: "/ˈklɪrli/", zh: "<ruby>清<rt>ㄑㄧㄥ</rt></ruby><ruby>楚<rt>ㄔㄨˇ</rt></ruby><ruby>地<rt>˙ㄉㄜ</rt></ruby>", ex: "See clearly.（清楚地看）" },
      { en: "somebody", type: "代名詞", ph: "/ˈsʌmbədi/", zh: "<ruby>某<rt>ㄇㄡˇ</rt></ruby><ruby>個<rt>˙ㄍㄜ</rt></ruby><ruby>人<rt>ㄖㄣˊ</rt></ruby>", ex: "Somebody I know.（我認識的人）" }
    ],
    mission: "聽到 <b>hero</b> 做出超人姿勢 🦸；聽到 <b>kiss</b> 對爸媽飛吻 💋；副歌 <b>something just like this</b> 一起指彼此大笑。"
  },
  {
    slug: "a-thousand-years",
    owner: "Ann 媽媽",
    ownerColor: "#2a9d8f",
    ownerAccent: "#1f6f66",
    title: "A Thousand Years",
    titleZh: "一千年",
    titleZhRuby: "<ruby>一<rt>ㄧˋ</rt></ruby><ruby>千<rt>ㄑㄧㄢ</rt></ruby><ruby>年<rt>ㄋㄧㄢˊ</rt></ruby>",
    artist: "Christina Perri",
    genre: "Ballad",
    year: "2011",
    album: "The Twilight Saga: Breaking Dawn 電影原聲帶",
    creator: "Christina Perri / David Hodges",
    cover: "assets/covers/A%20Thousand%20Years.jpg",
    mp3: "assets/mp3/A%20Thousand%20Years.mp3",
    lyricsDownload: "file:///Users/chennanhong/Desktop/AI%20%E8%82%B2%E5%85%92/%E8%8B%B1%E6%96%87%E6%AD%8C%E6%9B%B2/pumpkin_v3/02_%E6%AD%8C%E6%9B%B2%E5%AD%B8%E7%BF%92%E6%9C%AC/06_A_Thousand_Years.html",
    youtube: "https://www.youtube.com/watch?v=rtOvBOTyX00",
    genreDesc: "<ruby>抒<rt>ㄕㄨ</rt></ruby><ruby>情<rt>ㄑㄧㄥˊ</rt></ruby><ruby>慢<rt>ㄇㄢˋ</rt></ruby><ruby>歌<rt>ㄍㄜ</rt></ruby>(Ballad)。<ruby>鋼<rt>ㄍㄤ</rt></ruby><ruby>琴<rt>ㄑㄧㄣˊ</rt></ruby><ruby>加<rt>ㄐㄧㄚ</rt></ruby><ruby>弦<rt>ㄒㄧㄢˊ</rt></ruby><ruby>樂<rt>ㄩㄝˋ</rt></ruby>，<ruby>聽<rt>ㄊㄧㄥ</rt></ruby><ruby>了<rt>˙ㄌㄜ</rt></ruby><ruby>心<rt>ㄒㄧㄣ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby><ruby>會<rt>ㄏㄨㄟˋ</rt></ruby><ruby>暖<rt>ㄋㄨㄢˇ</rt></ruby><ruby>暖<rt>˙ㄋㄨㄢ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>。",
    meaning: "<ruby>這<rt>ㄓㄜˋ</rt></ruby><ruby>首<rt>ㄕㄡˇ</rt></ruby><ruby>歌<rt>ㄍㄜ</rt></ruby><ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>溫<rt>ㄨㄣ</rt></ruby><ruby>柔<rt>ㄖㄡˊ</rt></ruby>，<ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>個<rt>˙ㄍㄜ</rt></ruby><ruby>長<rt>ㄔㄤˊ</rt></ruby><ruby>長<rt>˙ㄔㄤ</rt></ruby><ruby>久<rt>ㄐㄧㄡˇ</rt></ruby><ruby>久<rt>˙ㄐㄧㄡ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>陪<rt>ㄆㄟˊ</rt></ruby><ruby>伴<rt>ㄅㄢˋ</rt></ruby>。<ruby>就<rt>ㄐㄧㄡˋ</rt></ruby><ruby>算<rt>ㄙㄨㄢˋ</rt></ruby><ruby>等<rt>ㄉㄥˇ</rt></ruby><ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>久<rt>ㄐㄧㄡˇ</rt></ruby>，<ruby>也<rt>ㄧㄝˇ</rt></ruby><ruby>願<rt>ㄩㄢˋ</rt></ruby><ruby>意<rt>ㄧˋ</rt></ruby><ruby>勇<rt>ㄩㄥˇ</rt></ruby><ruby>敢<rt>ㄍㄢˇ</rt></ruby><ruby>靠<rt>ㄎㄠˋ</rt></ruby><ruby>近<rt>ㄐㄧㄣˋ</rt></ruby><ruby>重<rt>ㄓㄨㄥˋ</rt></ruby><ruby>要<rt>ㄧㄠˋ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>人<rt>ㄖㄣˊ</rt></ruby>。",
    story: "這首歌很溫柔，像一個長長久久的陪伴。它在說：就算等很久，也願意勇敢靠近重要的人。",
    task: "跟著歌找出『時間』『勇氣』『心情變化』有關的字，再一起念一次。",
    practice: "How can I love when I am afraid? One step closer. Time has brought your heart to me.",
    celebrate: "Ann 媽媽帶來溫柔回合！這首歌適合抱抱、慢慢唱、慢慢學。",
    keyLyrics: [
      { en: "Heart beats fast.", zh: "<ruby>心<rt>ㄒㄧㄣ</rt></ruby><ruby>跳<rt>ㄊㄧㄠˋ</rt></ruby><ruby>加<rt>ㄐㄧㄚ</rt></ruby><ruby>速<rt>ㄙㄨˋ</rt></ruby>。" },
      { en: "One step closer.", zh: "<ruby>再<rt>ㄗㄞˋ</rt></ruby><ruby>靠<rt>ㄎㄠˋ</rt></ruby><ruby>近<rt>ㄐㄧㄣˋ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>步<rt>ㄅㄨˋ</rt></ruby>。" },
      { en: "I have loved you for a thousand years.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>愛<rt>ㄞˋ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>千<rt>ㄑㄧㄢ</rt></ruby><ruby>年<rt>ㄋㄧㄢˊ</rt></ruby><ruby>了<rt>˙ㄌㄜ</rt></ruby>。" },
      { en: "I'll love you for a thousand more.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>還<rt>ㄏㄞˊ</rt></ruby><ruby>會<rt>ㄏㄨㄟˋ</rt></ruby><ruby>再<rt>ㄗㄞˋ</rt></ruby><ruby>愛<rt>ㄞˋ</rt></ruby><ruby>你<rt>ㄋㄧˇ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>千<rt>ㄑㄧㄢ</rt></ruby><ruby>年<rt>ㄋㄧㄢˊ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "year", type: "名詞", ph: "/jɪr/", zh: "<ruby>年<rt>ㄋㄧㄢˊ</rt></ruby>", ex: "A new year.（新的一年）" },
      { en: "day", type: "名詞", ph: "/deɪ/", zh: "<ruby>日<rt>ㄖˋ</rt></ruby><ruby>子<rt>˙ㄗ</rt></ruby>", ex: "Every day.（每天）" },
      { en: "heart", type: "名詞", ph: "/hɑːrt/", zh: "<ruby>心<rt>ㄒㄧㄣ</rt></ruby>", ex: "Warm heart.（溫暖的心）" },
      { en: "love", type: "動詞", ph: "/lʌv/", zh: "<ruby>愛<rt>ㄞˋ</rt></ruby>", ex: "I love you.（我愛你）" },
      { en: "wait", type: "動詞", ph: "/weɪt/", zh: "<ruby>等<rt>ㄉㄥˇ</rt></ruby><ruby>待<rt>ㄉㄞˋ</rt></ruby>", ex: "Wait for me.（等我）" },
      { en: "time", type: "名詞", ph: "/taɪm/", zh: "<ruby>時<rt>ㄕˊ</rt></ruby><ruby>間<rt>ㄐㄧㄢ</rt></ruby>", ex: "Time goes fast.（時間過得快）" },
      { en: "stand", type: "動詞", ph: "/stænd/", zh: "<ruby>站<rt>ㄓㄢˋ</rt></ruby><ruby>立<rt>ㄌㄧˋ</rt></ruby>", ex: "Stand up.（站起來）" },
      { en: "close", type: "形容詞", ph: "/kloʊs/", zh: "<ruby>靠<rt>ㄎㄠˋ</rt></ruby><ruby>近<rt>ㄐㄧㄣˋ</rt></ruby>", ex: "So close.（好近）" },
      { en: "brave", type: "形容詞", ph: "/breɪv/", zh: "<ruby>勇<rt>ㄩㄥˇ</rt></ruby><ruby>敢<rt>ㄍㄢˇ</rt></ruby>", ex: "Be brave.（要勇敢）" },
      { en: "hold", type: "動詞", ph: "/hoʊld/", zh: "<ruby>握<rt>ㄨㄛˋ</rt></ruby><ruby>住<rt>ㄓㄨˋ</rt></ruby>", ex: "Hold on.（抓緊）" },
      { en: "step", type: "名詞", ph: "/step/", zh: "<ruby>步<rt>ㄅㄨˋ</rt></ruby><ruby>伐<rt>ㄈㄚˊ</rt></ruby>", ex: "One step.（一步）" },
      { en: "fall", type: "動詞", ph: "/fɔːl/", zh: "<ruby>跌<rt>ㄉㄧㄝˊ</rt></ruby><ruby>倒<rt>ㄉㄠˇ</rt></ruby>", ex: "Don't fall.（不要跌倒）" }
    ],
    advancedVocab: [
      { en: "promises", type: "名詞", ph: "/ˈprɑːmɪsɪz/", zh: "<ruby>承<rt>ㄔㄥˊ</rt></ruby><ruby>諾<rt>ㄋㄨㄛˋ</rt></ruby>", ex: "Keep promises.（守承諾）" },
      { en: "afraid", type: "形容詞", ph: "/əˈfreɪd/", zh: "<ruby>害<rt>ㄏㄞˋ</rt></ruby><ruby>怕<rt>ㄆㄚˋ</rt></ruby>", ex: "Don't be afraid.（別害怕）" },
      { en: "doubt", type: "名詞", ph: "/daʊt/", zh: "<ruby>懷<rt>ㄏㄨㄞˊ</rt></ruby><ruby>疑<rt>ㄧˊ</rt></ruby>", ex: "No doubt.（毫無疑問）" },
      { en: "suddenly", type: "副詞", ph: "/ˈsʌdənli/", zh: "<ruby>突<rt>ㄊㄨˊ</rt></ruby><ruby>然<rt>ㄖㄢˊ</rt></ruby>", ex: "Suddenly rain.（突然下雨）" },
      { en: "beauty", type: "名詞", ph: "/ˈbjuːti/", zh: "<ruby>美<rt>ㄇㄟˇ</rt></ruby><ruby>麗<rt>ㄌㄧˋ</rt></ruby>", ex: "True beauty.（真正的美）" },
      { en: "breath", type: "名詞", ph: "/breθ/", zh: "<ruby>呼<rt>ㄏㄨ</rt></ruby><ruby>吸<rt>ㄒㄧ</rt></ruby>", ex: "Take a breath.（深呼吸）" },
      { en: "thousand", type: "數詞", ph: "/ˈθaʊzənd/", zh: "<ruby>一<rt>ㄧˋ</rt></ruby><ruby>千<rt>ㄑㄧㄢ</rt></ruby>", ex: "A thousand years.（一千年）" },
      { en: "believed", type: "動詞", ph: "/bɪˈliːvd/", zh: "<ruby>相<rt>ㄒㄧㄤ</rt></ruby><ruby>信<rt>ㄒㄧㄣˋ</rt></ruby><ruby>過<rt>ㄍㄨㄛˋ</rt></ruby>", ex: "I believed you.（我相信過你）" }
    ],
    mission: "聽到 <b>heart</b> 雙手比愛心 ❤️；聽到 <b>year</b> 雙手做翻書動作；副歌 <b>thousand years</b> 全家擁抱搖擺。"
  },
  {
    slug: "zoo",
    owner: "睿寶",
    ownerColor: "#7b5cff",
    ownerAccent: "#5a3bd4",
    title: "Zoo",
    titleZh: "動物園",
    titleZhRuby: "<ruby>動<rt>ㄉㄨㄥˋ</rt></ruby><ruby>物<rt>ㄨˋ</rt></ruby><ruby>園<rt>ㄩㄢˊ</rt></ruby>",
    artist: "Shakira",
    genre: "Dance Pop",
    year: "2024",
    album: "Las Mujeres Ya No Lloran",
    creator: "Shakira",
    cover: "assets/covers/ZOO.jpg",
    mp3: "assets/mp3/ZOO.mp3",
    lyricsDownload: "file:///Users/chennanhong/Desktop/AI%20%E8%82%B2%E5%85%92/%E8%8B%B1%E6%96%87%E6%AD%8C%E6%9B%B2/pumpkin_v3/02_%E6%AD%8C%E6%9B%B2%E5%AD%B8%E7%BF%92%E6%9C%AC/07_Zoo.html",
    youtube: "https://www.youtube.com/watch?v=Kw3935PH01E",
    genreDesc: "<ruby>舞<rt>ㄨˇ</rt></ruby><ruby>曲<rt>ㄑㄩˇ</rt></ruby><ruby>流<rt>ㄌㄧㄡˊ</rt></ruby><ruby>行<rt>ㄒㄧㄥˊ</rt></ruby>(Dance Pop)。<ruby>節<rt>ㄐㄧㄝˊ</rt></ruby><ruby>奏<rt>ㄗㄡˋ</rt></ruby><ruby>超<rt>ㄔㄠ</rt></ruby><ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>力<rt>ㄌㄧˋ</rt></ruby>，<ruby>聽<rt>ㄊㄧㄥ</rt></ruby><ruby>了<rt>˙ㄌㄜ</rt></ruby><ruby>會<rt>ㄏㄨㄟˋ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>跳<rt>ㄊㄧㄠˋ</rt></ruby><ruby>舞<rt>ㄨˇ</rt></ruby>。",
    meaning: "<ruby>這<rt>ㄓㄜˋ</rt></ruby><ruby>首<rt>ㄕㄡˇ</rt></ruby><ruby>歌<rt>ㄍㄜ</rt></ruby><ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>開<rt>ㄎㄞ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>場<rt>ㄔㄤˇ</rt></ruby><ruby>動<rt>ㄉㄨㄥˋ</rt></ruby><ruby>物<rt>ㄨˋ</rt></ruby><ruby>派<rt>ㄆㄞˋ</rt></ruby><ruby>對<rt>ㄉㄨㄟˋ</rt></ruby>。<ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>熱<rt>ㄖㄜˋ</rt></ruby><ruby>鬧<rt>ㄋㄠˋ</rt></ruby>，<ruby>也<rt>ㄧㄝˇ</rt></ruby><ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>適<rt>ㄕˋ</rt></ruby><ruby>合<rt>ㄏㄜˊ</rt></ruby><ruby>讓<rt>ㄖㄤˋ</rt></ruby><ruby>孩<rt>ㄏㄞˊ</rt></ruby><ruby>子<rt>˙ㄗ</rt></ruby><ruby>邊<rt>ㄅㄧㄢ</rt></ruby><ruby>唱<rt>ㄔㄤˋ</rt></ruby><ruby>邊<rt>˙ㄅㄧㄢ</rt></ruby><ruby>動<rt>ㄉㄨㄥˋ</rt></ruby>。",
    story: "這首歌像在開動物派對，很熱鬧、很有力氣，也很適合讓孩子邊唱邊動。",
    task: "一邊聽一邊找歌裡和派對、能量、城市、動物感覺有關的詞。",
    practice: "Come on, get on up. We are wild. Do not let this moment fade away.",
    celebrate: "睿寶回合大爆發！彩帶飛起來，今天全家一起變成動物派對小隊。",
    keyLyrics: [
      { en: "Come on, get on up.", zh: "<ruby>來<rt>ㄌㄞˊ</rt></ruby><ruby>吧<rt>˙ㄅㄚ</rt></ruby>，<ruby>起<rt>ㄑㄧˇ</rt></ruby><ruby>身<rt>ㄕㄣ</rt></ruby><ruby>嗨<rt>ㄏㄞ</rt></ruby><ruby>起<rt>ㄑㄧˇ</rt></ruby><ruby>來<rt>˙ㄌㄞ</rt></ruby>！" },
      { en: "We are wild, we cannot be tamed.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>們<rt>˙ㄇㄣ</rt></ruby><ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>狂<rt>ㄎㄨㄤˊ</rt></ruby><ruby>野<rt>ㄧㄝˇ</rt></ruby>，<ruby>沒<rt>ㄇㄟˊ</rt></ruby><ruby>辦<rt>ㄅㄢˋ</rt></ruby><ruby>法<rt>ㄈㄚˇ</rt></ruby><ruby>被<rt>ㄅㄟˋ</rt></ruby><ruby>馴<rt>ㄒㄩㄣˋ</rt></ruby><ruby>服<rt>ㄈㄨˊ</rt></ruby>。" },
      { en: "Turning the floor into a zoo.", zh: "<ruby>把<rt>ㄅㄚˇ</rt></ruby><ruby>地<rt>ㄉㄧˋ</rt></ruby><ruby>板<rt>ㄅㄢˇ</rt></ruby><ruby>變<rt>ㄅㄧㄢˋ</rt></ruby><ruby>成<rt>ㄔㄥˊ</rt></ruby><ruby>動<rt>ㄉㄨㄥˋ</rt></ruby><ruby>物<rt>ㄨˋ</rt></ruby><ruby>園<rt>ㄩㄢˊ</rt></ruby>。" },
      { en: "Don't let this moment fade away.", zh: "<ruby>別<rt>ㄅㄧㄝˊ</rt></ruby><ruby>讓<rt>ㄖㄤˋ</rt></ruby><ruby>這<rt>ㄓㄜˋ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>刻<rt>ㄎㄜˋ</rt></ruby><ruby>消<rt>ㄒㄧㄠ</rt></ruby><ruby>失<rt>ㄕ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "zoo", type: "名詞", ph: "/zuː/", zh: "<ruby>動<rt>ㄉㄨㄥˋ</rt></ruby><ruby>物<rt>ㄨˋ</rt></ruby><ruby>園<rt>ㄩㄢˊ</rt></ruby>", ex: "Go to the zoo.（去動物園）" },
      { en: "wild", type: "形容詞", ph: "/waɪld/", zh: "<ruby>狂<rt>ㄎㄨㄤˊ</rt></ruby><ruby>野<rt>ㄧㄝˇ</rt></ruby>", ex: "Wild animal.（野生動物）" },
      { en: "dance", type: "動詞", ph: "/dæns/", zh: "<ruby>跳<rt>ㄊㄧㄠˋ</rt></ruby><ruby>舞<rt>ㄨˇ</rt></ruby>", ex: "Let's dance.（我們來跳舞）" },
      { en: "party", type: "名詞", ph: "/ˈpɑːrti/", zh: "<ruby>派<rt>ㄆㄞˋ</rt></ruby><ruby>對<rt>ㄉㄨㄟˋ</rt></ruby>", ex: "Big party.（大派對）" },
      { en: "city", type: "名詞", ph: "/ˈsɪti/", zh: "<ruby>城<rt>ㄔㄥˊ</rt></ruby><ruby>市<rt>ㄕˋ</rt></ruby>", ex: "Big city.（大城市）" },
      { en: "jump", type: "動詞", ph: "/dʒʌmp/", zh: "<ruby>跳<rt>ㄊㄧㄠˋ</rt></ruby>", ex: "Jump high.（跳得高）" },
      { en: "free", type: "形容詞", ph: "/friː/", zh: "<ruby>自<rt>ㄗˋ</rt></ruby><ruby>由<rt>ㄧㄡˊ</rt></ruby>", ex: "Feel free.（感到自由）" },
      { en: "run", type: "動詞", ph: "/rʌn/", zh: "<ruby>奔<rt>ㄅㄣ</rt></ruby><ruby>跑<rt>ㄆㄠˇ</rt></ruby>", ex: "Run fast.（跑得快）" },
      { en: "floor", type: "名詞", ph: "/flɔːr/", zh: "<ruby>地<rt>ㄉㄧˋ</rt></ruby><ruby>板<rt>ㄅㄢˇ</rt></ruby>", ex: "Wooden floor.（木地板）" },
      { en: "loud", type: "形容詞", ph: "/laʊd/", zh: "<ruby>大<rt>ㄉㄚˋ</rt></ruby><ruby>聲<rt>ㄕㄥ</rt></ruby>", ex: "Too loud.（太大聲）" },
      { en: "high", type: "形容詞", ph: "/haɪ/", zh: "<ruby>高<rt>ㄍㄠ</rt></ruby>", ex: "Higher.（更高）" },
      { en: "fade", type: "動詞", ph: "/feɪd/", zh: "<ruby>消<rt>ㄒㄧㄠ</rt></ruby><ruby>失<rt>ㄕ</rt></ruby>", ex: "Don't fade.（別消失）" }
    ],
    advancedVocab: [
      { en: "tamed", type: "動詞", ph: "/teɪmd/", zh: "<ruby>被<rt>ㄅㄟˋ</rt></ruby><ruby>馴<rt>ㄒㄩㄣˋ</rt></ruby><ruby>服<rt>ㄈㄨˊ</rt></ruby>", ex: "Can't be tamed.（無法馴服）" },
      { en: "concrete", type: "名詞", ph: "/ˈkɑːnkriːt/", zh: "<ruby>水<rt>ㄕㄨㄟˇ</rt></ruby><ruby>泥<rt>ㄋㄧˊ</rt></ruby>", ex: "Concrete jungle.（水泥叢林）" },
      { en: "jungle", type: "名詞", ph: "/ˈdʒʌŋɡl/", zh: "<ruby>叢<rt>ㄘㄨㄥˊ</rt></ruby><ruby>林<rt>ㄌㄧㄣˊ</rt></ruby>", ex: "Deep jungle.（深叢林）" },
      { en: "release", type: "動詞", ph: "/rɪˈliːs/", zh: "<ruby>釋<rt>ㄕˋ</rt></ruby><ruby>放<rt>ㄈㄤˋ</rt></ruby>", ex: "Release energy.（釋放能量）" },
      { en: "energy", type: "名詞", ph: "/ˈenərdʒi/", zh: "<ruby>能<rt>ㄋㄥˊ</rt></ruby><ruby>量<rt>ㄌㄧㄤˋ</rt></ruby>", ex: "Good energy.（好能量）" },
      { en: "celebrate", type: "動詞", ph: "/ˈseləbreɪt/", zh: "<ruby>慶<rt>ㄑㄧㄥˋ</rt></ruby><ruby>祝<rt>ㄓㄨˋ</rt></ruby>", ex: "Let's celebrate.（我們慶祝）" },
      { en: "moment", type: "名詞", ph: "/ˈmoʊmənt/", zh: "<ruby>瞬<rt>ㄕㄨㄣˋ</rt></ruby><ruby>間<rt>ㄐㄧㄢ</rt></ruby>", ex: "This moment.（這一刻）" },
      { en: "fiesta", type: "名詞", ph: "/fiˈestə/", zh: "<ruby>派<rt>ㄆㄞˋ</rt></ruby><ruby>對<rt>ㄉㄨㄟˋ</rt></ruby>", ex: "Big fiesta.（大派對）" }
    ],
    mission: "聽到 <b>zoo</b> 做出自己喜歡的動物 🦁；聽到 <b>dance</b> 全家站起來搖擺；副歌 <b>come on get on up</b> 用力跳！"
  },
  {
    slug: "soda-pop",
    owner: "睿寶",
    ownerColor: "#7b5cff",
    ownerAccent: "#5a3bd4",
    title: "Soda Pop",
    titleZh: "汽水",
    titleZhRuby: "<ruby>汽<rt>ㄑㄧˋ</rt></ruby><ruby>水<rt>ㄕㄨㄟˇ</rt></ruby>",
    artist: "Saja Boys (KPop Demon Hunters)",
    genre: "Dance Pop",
    year: "2025",
    album: "KPop Demon Hunters 原聲帶",
    creator: "EJAE / Teddy Park",
    cover: "assets/covers/Soda%20Pop.jpg",
    mp3: "assets/mp3/Soda%20Pop.mp3",
    lyricsDownload: "file:///Users/chennanhong/Desktop/AI%20%E8%82%B2%E5%85%92/%E8%8B%B1%E6%96%87%E6%AD%8C%E6%9B%B2/pumpkin_v3/02_%E6%AD%8C%E6%9B%B2%E5%AD%B8%E7%BF%92%E6%9C%AC/08_Soda_Pop.html",
    youtube: "https://www.youtube.com/watch?v=983bBbJx0Mk",
    genreDesc: "<ruby>舞<rt>ㄨˇ</rt></ruby><ruby>曲<rt>ㄑㄩˇ</rt></ruby><ruby>流<rt>ㄌㄧㄡˊ</rt></ruby><ruby>行<rt>ㄒㄧㄥˊ</rt></ruby>。<ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>汽<rt>ㄑㄧˋ</rt></ruby><ruby>水<rt>ㄕㄨㄟˇ</rt></ruby><ruby>一<rt>ㄧˊ</rt></ruby><ruby>樣<rt>ㄧㄤˋ</rt></ruby><ruby>甜<rt>ㄊㄧㄢˊ</rt></ruby><ruby>甜<rt>˙ㄊㄧㄢ</rt></ruby>、<ruby>冒<rt>ㄇㄠˋ</rt></ruby><ruby>泡<rt>ㄆㄠˋ</rt></ruby><ruby>泡<rt>˙ㄆㄠ</rt></ruby>、<ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>跳<rt>ㄊㄧㄠˋ</rt></ruby>。",
    meaning: "<ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>汽<rt>ㄑㄧˋ</rt></ruby><ruby>水<rt>ㄕㄨㄟˇ</rt></ruby><ruby>一<rt>ㄧˊ</rt></ruby><ruby>樣<rt>ㄧㄤˋ</rt></ruby>，<ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>甜<rt>ㄊㄧㄢˊ</rt></ruby><ruby>甜<rt>˙ㄊㄧㄢ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>感<rt>ㄍㄢˇ</rt></ruby><ruby>覺<rt>ㄐㄩㄝˊ</rt></ruby>，<ruby>也<rt>ㄧㄝˇ</rt></ruby><ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>冒<rt>ㄇㄠˋ</rt></ruby><ruby>泡<rt>ㄆㄠˋ</rt></ruby><ruby>泡<rt>˙ㄆㄠ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>活<rt>ㄏㄨㄛˊ</rt></ruby><ruby>力<rt>ㄌㄧˋ</rt></ruby>。<ruby>很<rt>ㄏㄣˇ</rt></ruby><ruby>適<rt>ㄕˋ</rt></ruby><ruby>合<rt>ㄏㄜˊ</rt></ruby><ruby>讓<rt>ㄖㄤˋ</rt></ruby><ruby>孩<rt>ㄏㄞˊ</rt></ruby><ruby>子<rt>˙ㄗ</rt></ruby><ruby>用<rt>ㄩㄥˋ</rt></ruby><ruby>身<rt>ㄕㄣ</rt></ruby><ruby>體<rt>ㄊㄧˇ</rt></ruby><ruby>感<rt>ㄍㄢˇ</rt></ruby><ruby>受<rt>ㄕㄡˋ</rt></ruby><ruby>節<rt>ㄐㄧㄝˊ</rt></ruby><ruby>奏<rt>ㄗㄡˋ</rt></ruby>。",
    story: "像汽水一樣，有甜甜的感覺，也有冒泡泡的活力。很適合讓孩子用身體感受節奏。",
    task: "先找出歌裡和飲料有關的詞，再找出『熱』『涼』『冒泡』這些感覺詞。",
    practice: "Every sip makes me want more. Cool me down. Every little drip and drop fizz and pop.",
    celebrate: "輪到睿寶最閃亮的歌啦！這首超有派對感，準備開心跳起來。",
    keyLyrics: [
      { en: "Fill me up like a soda pop.", zh: "<ruby>把<rt>ㄅㄚˇ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>填<rt>ㄊㄧㄢˊ</rt></ruby><ruby>滿<rt>ㄇㄢˇ</rt></ruby>，<ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>瓶<rt>ㄆㄧㄥˊ</rt></ruby><ruby>汽<rt>ㄑㄧˋ</rt></ruby><ruby>水<rt>ㄕㄨㄟˇ</rt></ruby>。" },
      { en: "Every sip makes me want more.", zh: "<ruby>每<rt>ㄇㄟˇ</rt></ruby><ruby>喝<rt>ㄏㄜ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>口<rt>ㄎㄡˇ</rt></ruby><ruby>都<rt>ㄉㄡ</rt></ruby><ruby>想<rt>ㄒㄧㄤˇ</rt></ruby><ruby>再<rt>ㄗㄞˋ</rt></ruby><ruby>來<rt>ㄌㄞˊ</rt></ruby><ruby>更<rt>ㄍㄥˋ</rt></ruby><ruby>多<rt>ㄉㄨㄛ</rt></ruby>。" },
      { en: "Cool me down.", zh: "<ruby>讓<rt>ㄖㄤˋ</rt></ruby><ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>涼<rt>ㄌㄧㄤˊ</rt></ruby><ruby>下<rt>ㄒㄧㄚˋ</rt></ruby><ruby>來<rt>˙ㄌㄞ</rt></ruby>。" },
      { en: "Every little drip and drop, fizz and pop.", zh: "<ruby>每<rt>ㄇㄟˇ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>滴<rt>ㄉㄧ</rt></ruby><ruby>每<rt>ㄇㄟˇ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>滴<rt>ㄉㄧ</rt></ruby>，<ruby>冒<rt>ㄇㄠˋ</rt></ruby><ruby>泡<rt>ㄆㄠˋ</rt></ruby><ruby>又<rt>ㄧㄡˋ</rt></ruby><ruby>爆<rt>ㄅㄠˋ</rt></ruby><ruby>開<rt>ㄎㄞ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "soda", type: "名詞", ph: "/ˈsoʊdə/", zh: "<ruby>汽<rt>ㄑㄧˋ</rt></ruby><ruby>水<rt>ㄕㄨㄟˇ</rt></ruby>", ex: "Cold soda.（冰汽水）" },
      { en: "pop", type: "名詞", ph: "/pɑːp/", zh: "<ruby>爆<rt>ㄅㄠˋ</rt></ruby><ruby>開<rt>ㄎㄞ</rt></ruby>", ex: "Pop sound.（爆開的聲音）" },
      { en: "drink", type: "名詞", ph: "/drɪŋk/", zh: "<ruby>飲<rt>ㄧㄣˇ</rt></ruby><ruby>料<rt>ㄌㄧㄠˋ</rt></ruby>", ex: "Cold drink.（冷飲）" },
      { en: "sweet", type: "形容詞", ph: "/swiːt/", zh: "<ruby>甜<rt>ㄊㄧㄢˊ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Sweet taste.（甜味）" },
      { en: "bubble", type: "名詞", ph: "/ˈbʌbl/", zh: "<ruby>泡<rt>ㄆㄠˋ</rt></ruby><ruby>泡<rt>˙ㄆㄠ</rt></ruby>", ex: "Many bubbles.（很多泡泡）" },
      { en: "cool", type: "形容詞", ph: "/kuːl/", zh: "<ruby>涼<rt>ㄌㄧㄤˊ</rt></ruby><ruby>爽<rt>ㄕㄨㄤˇ</rt></ruby>", ex: "Cool air.（涼爽空氣）" },
      { en: "hot", type: "形容詞", ph: "/hɑːt/", zh: "<ruby>熱<rt>ㄖㄜˋ</rt></ruby>", ex: "Hot day.（熱天）" },
      { en: "taste", type: "名詞", ph: "/teɪst/", zh: "<ruby>味<rt>ㄨㄟˋ</rt></ruby><ruby>道<rt>ㄉㄠˋ</rt></ruby>", ex: "Good taste.（好味道）" },
      { en: "cup", type: "名詞", ph: "/kʌp/", zh: "<ruby>杯<rt>ㄅㄟ</rt></ruby><ruby>子<rt>˙ㄗ</rt></ruby>", ex: "My cup.（我的杯子）" },
      { en: "pour", type: "動詞", ph: "/pɔːr/", zh: "<ruby>倒<rt>ㄉㄠˋ</rt></ruby><ruby>出<rt>ㄔㄨ</rt></ruby>", ex: "Pour water.（倒水）" },
      { en: "more", type: "形容詞", ph: "/mɔːr/", zh: "<ruby>更<rt>ㄍㄥˋ</rt></ruby><ruby>多<rt>ㄉㄨㄛ</rt></ruby>", ex: "One more.（再一個）" },
      { en: "drop", type: "名詞", ph: "/drɑːp/", zh: "<ruby>一<rt>ㄧˋ</rt></ruby><ruby>滴<rt>ㄉㄧ</rt></ruby>", ex: "A water drop.（一滴水）" }
    ],
    advancedVocab: [
      { en: "refreshing", type: "形容詞", ph: "/rɪˈfreʃɪŋ/", zh: "<ruby>清<rt>ㄑㄧㄥ</rt></ruby><ruby>爽<rt>ㄕㄨㄤˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "So refreshing.（好清爽）" },
      { en: "sip", type: "名詞", ph: "/sɪp/", zh: "<ruby>一<rt>ㄧˋ</rt></ruby><ruby>小<rt>ㄒㄧㄠˇ</rt></ruby><ruby>口<rt>ㄎㄡˇ</rt></ruby>", ex: "Take a sip.（喝一小口）" },
      { en: "flip", type: "動詞", ph: "/flɪp/", zh: "<ruby>掀<rt>ㄒㄧㄢ</rt></ruby><ruby>開<rt>ㄎㄞ</rt></ruby>", ex: "Flip the top.（掀開蓋子）" },
      { en: "drip", type: "動詞", ph: "/drɪp/", zh: "<ruby>滴<rt>ㄉㄧ</rt></ruby><ruby>下<rt>ㄒㄧㄚˋ</rt></ruby>", ex: "Drip, drop.（一滴一滴）" },
      { en: "fizz", type: "動詞", ph: "/fɪz/", zh: "<ruby>冒<rt>ㄇㄠˋ</rt></ruby><ruby>泡<rt>ㄆㄠˋ</rt></ruby>", ex: "Soda fizz.（汽水冒泡）" },
      { en: "empty", type: "形容詞", ph: "/ˈempti/", zh: "<ruby>空<rt>ㄎㄨㄥ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby>", ex: "Empty cup.（空杯子）" },
      { en: "enough", type: "副詞", ph: "/ɪˈnʌf/", zh: "<ruby>足<rt>ㄗㄨˊ</rt></ruby><ruby>夠<rt>ㄍㄡˋ</rt></ruby>", ex: "Enough!（夠了！）" },
      { en: "snacks", type: "名詞", ph: "/snæks/", zh: "<ruby>零<rt>ㄌㄧㄥˊ</rt></ruby><ruby>食<rt>ㄕˊ</rt></ruby>", ex: "Tasty snacks.（好吃零食）" }
    ],
    mission: "聽到 <b>pop</b> 雙手拍手一次 👏；聽到 <b>bubble</b> 做吐泡泡動作；副歌 <b>fizz and pop</b> 全家轉圈圈！"
  },
  {
    slug: "free",
    owner: "睿寶",
    ownerColor: "#7b5cff",
    ownerAccent: "#5a3bd4",
    title: "Free",
    titleZh: "自由",
    titleZhRuby: "<ruby>自<rt>ㄗˋ</rt></ruby><ruby>由<rt>ㄧㄡˊ</rt></ruby>",
    artist: "Rumi & Jinu (KPop Demon Hunters)",
    genre: "Pop Ballad",
    year: "2025",
    album: "KPop Demon Hunters 原聲帶",
    creator: "EJAE / Mark Sonnenblick",
    cover: "assets/covers/Free.jpg",
    mp3: "assets/mp3/Free.mp3",
    lyricsDownload: "file:///Users/chennanhong/Desktop/AI%20%E8%82%B2%E5%85%92/%E8%8B%B1%E6%96%87%E6%AD%8C%E6%9B%B2/pumpkin_v3/02_%E6%AD%8C%E6%9B%B2%E5%AD%B8%E7%BF%92%E6%9C%AC/09_Free.html",
    youtube: "https://www.youtube.com/watch?v=fjOeJssZX_Q",
    genreDesc: "<ruby>流<rt>ㄌㄧㄡˊ</rt></ruby><ruby>行<rt>ㄒㄧㄥˊ</rt></ruby><ruby>抒<rt>ㄕㄨ</rt></ruby><ruby>情<rt>ㄑㄧㄥˊ</rt></ruby>。<ruby>前<rt>ㄑㄧㄢˊ</rt></ruby><ruby>半<rt>ㄅㄢˋ</rt></ruby><ruby>段<rt>ㄉㄨㄢˋ</rt></ruby><ruby>安<rt>ㄢ</rt></ruby><ruby>靜<rt>ㄐㄧㄥˋ</rt></ruby>，<ruby>後<rt>ㄏㄡˋ</rt></ruby><ruby>半<rt>ㄅㄢˋ</rt></ruby><ruby>段<rt>ㄉㄨㄢˋ</rt></ruby><ruby>越<rt>ㄩㄝˋ</rt></ruby><ruby>來<rt>ㄌㄞˊ</rt></ruby><ruby>越<rt>ㄩㄝˋ</rt></ruby><ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>力<rt>ㄌㄧˋ</rt></ruby><ruby>氣<rt>˙ㄑㄧ</rt></ruby>。",
    meaning: "<ruby>這<rt>ㄓㄜˋ</rt></ruby><ruby>首<rt>ㄕㄡˇ</rt></ruby><ruby>歌<rt>ㄍㄜ</rt></ruby><ruby>像<rt>ㄒㄧㄤˋ</rt></ruby><ruby>在<rt>ㄗㄞˋ</rt></ruby><ruby>說<rt>ㄕㄨㄛ</rt></ruby>：<ruby>把<rt>ㄅㄚˇ</rt></ruby><ruby>心<rt>ㄒㄧㄣ</rt></ruby><ruby>裡<rt>ㄌㄧˇ</rt></ruby><ruby>的<rt>˙ㄉㄜ</rt></ruby><ruby>小<rt>ㄒㄧㄠˇ</rt></ruby><ruby>祕<rt>ㄇㄧˋ</rt></ruby><ruby>密<rt>ㄇㄧˋ</rt></ruby><ruby>說<rt>ㄕㄨㄛ</rt></ruby><ruby>出<rt>ㄔㄨ</rt></ruby><ruby>來<rt>ㄌㄞˊ</rt></ruby><ruby>之<rt>ㄓ</rt></ruby><ruby>後<rt>ㄏㄡˋ</rt></ruby>，<ruby>人<rt>ㄖㄣˊ</rt></ruby><ruby>會<rt>ㄏㄨㄟˋ</rt></ruby><ruby>慢<rt>ㄇㄢˋ</rt></ruby><ruby>慢<rt>˙ㄇㄢ</rt></ruby><ruby>變<rt>ㄅㄧㄢˋ</rt></ruby><ruby>輕<rt>ㄑㄧㄥ</rt></ruby><ruby>鬆<rt>ㄙㄨㄥ</rt></ruby>，<ruby>也<rt>ㄧㄝˇ</rt></ruby><ruby>更<rt>ㄍㄥˋ</rt></ruby><ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>勇<rt>ㄩㄥˇ</rt></ruby><ruby>氣<rt>˙ㄑㄧ</rt></ruby>。",
    story: "這首歌像在說：把心裡的小祕密說出來之後，人會慢慢變輕鬆，也更有勇氣。",
    task: "先找出歌裡和『心情』『害怕』『改變』『面對』有關的字，再一起說出最有感的一個。",
    practice: "We cannot fix it if we never face it. Let the past be the past. We could be free.",
    celebrate: "睿寶抽中了自由歌！今天我們一起把勇氣打開，輕輕鬆鬆學英文。",
    keyLyrics: [
      { en: "We've been suffocating under secrets.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>們<rt>˙ㄇㄣ</rt></ruby><ruby>一<rt>ㄧˋ</rt></ruby><ruby>直<rt>ㄓˊ</rt></ruby><ruby>被<rt>ㄅㄟˋ</rt></ruby><ruby>祕<rt>ㄇㄧˋ</rt></ruby><ruby>密<rt>ㄇㄧˋ</rt></ruby><ruby>壓<rt>ㄧㄚ</rt></ruby><ruby>得<rt>˙ㄉㄜ</rt></ruby><ruby>喘<rt>ㄔㄨㄢˇ</rt></ruby><ruby>不<rt>ㄅㄨˊ</rt></ruby><ruby>過<rt>ㄍㄨㄛˋ</rt></ruby><ruby>氣<rt>ㄑㄧˋ</rt></ruby>。" },
      { en: "We can't fix it if we never face it.", zh: "<ruby>不<rt>ㄅㄨˊ</rt></ruby><ruby>面<rt>ㄇㄧㄢˋ</rt></ruby><ruby>對<rt>ㄉㄨㄟˋ</rt></ruby><ruby>就<rt>ㄐㄧㄡˋ</rt></ruby><ruby>沒<rt>ㄇㄟˊ</rt></ruby><ruby>辦<rt>ㄅㄢˋ</rt></ruby><ruby>法<rt>ㄈㄚˇ</rt></ruby><ruby>把<rt>ㄅㄚˇ</rt></ruby><ruby>它<rt>ㄊㄚ</rt></ruby><ruby>修<rt>ㄒㄧㄡ</rt></ruby><ruby>好<rt>ㄏㄠˇ</rt></ruby>。" },
      { en: "We could be free.", zh: "<ruby>我<rt>ㄨㄛˇ</rt></ruby><ruby>們<rt>˙ㄇㄣ</rt></ruby><ruby>可<rt>ㄎㄜˇ</rt></ruby><ruby>以<rt>ㄧˇ</rt></ruby><ruby>自<rt>ㄗˋ</rt></ruby><ruby>由<rt>ㄧㄡˊ</rt></ruby>。" },
      { en: "Let the past be the past.", zh: "<ruby>讓<rt>ㄖㄤˋ</rt></ruby><ruby>過<rt>ㄍㄨㄛˋ</rt></ruby><ruby>去<rt>ㄑㄩˋ</rt></ruby><ruby>成<rt>ㄔㄥˊ</rt></ruby><ruby>為<rt>ㄨㄟˊ</rt></ruby><ruby>過<rt>ㄍㄨㄛˋ</rt></ruby><ruby>去<rt>ㄑㄩˋ</rt></ruby>。" }
    ],
    basicVocab: [
      { en: "free", type: "形容詞", ph: "/friː/", zh: "<ruby>自<rt>ㄗˋ</rt></ruby><ruby>由<rt>ㄧㄡˊ</rt></ruby>", ex: "Feel free.（感覺自由）" },
      { en: "heart", type: "名詞", ph: "/hɑːrt/", zh: "<ruby>心<rt>ㄒㄧㄣ</rt></ruby>", ex: "My heart.（我的心）" },
      { en: "secret", type: "名詞", ph: "/ˈsiːkrət/", zh: "<ruby>祕<rt>ㄇㄧˋ</rt></ruby><ruby>密<rt>ㄇㄧˋ</rt></ruby>", ex: "A little secret.（小祕密）" },
      { en: "fear", type: "名詞", ph: "/fɪr/", zh: "<ruby>害<rt>ㄏㄞˋ</rt></ruby><ruby>怕<rt>ㄆㄚˋ</rt></ruby>", ex: "Face fear.（面對害怕）" },
      { en: "dark", type: "名詞", ph: "/dɑːrk/", zh: "<ruby>黑<rt>ㄏㄟ</rt></ruby><ruby>暗<rt>ㄢˋ</rt></ruby>", ex: "Dark side.（黑暗面）" },
      { en: "light", type: "名詞", ph: "/laɪt/", zh: "<ruby>光<rt>ㄍㄨㄤ</rt></ruby>", ex: "Bright light.（明亮的光）" },
      { en: "brave", type: "形容詞", ph: "/breɪv/", zh: "<ruby>勇<rt>ㄩㄥˇ</rt></ruby><ruby>敢<rt>ㄍㄢˇ</rt></ruby>", ex: "Be brave.（勇敢）" },
      { en: "wing", type: "名詞", ph: "/wɪŋ/", zh: "<ruby>翅<rt>ㄔˋ</rt></ruby><ruby>膀<rt>ㄅㄤˇ</rt></ruby>", ex: "Open wings.（張開翅膀）" },
      { en: "fly", type: "動詞", ph: "/flaɪ/", zh: "<ruby>飛<rt>ㄈㄟ</rt></ruby>", ex: "Fly high.（飛高）" },
      { en: "sky", type: "名詞", ph: "/skaɪ/", zh: "<ruby>天<rt>ㄊㄧㄢ</rt></ruby><ruby>空<rt>ㄎㄨㄥ</rt></ruby>", ex: "Blue sky.（藍天）" },
      { en: "face", type: "動詞", ph: "/feɪs/", zh: "<ruby>面<rt>ㄇㄧㄢˋ</rt></ruby><ruby>對<rt>ㄉㄨㄟˋ</rt></ruby>", ex: "Face it.（面對它）" },
      { en: "past", type: "名詞", ph: "/pæst/", zh: "<ruby>過<rt>ㄍㄨㄛˋ</rt></ruby><ruby>去<rt>ㄑㄩˋ</rt></ruby>", ex: "The past.（過去）" }
    ],
    advancedVocab: [
      { en: "suffocating", type: "動詞", ph: "/ˈsʌfəkeɪtɪŋ/", zh: "<ruby>喘<rt>ㄔㄨㄢˇ</rt></ruby><ruby>不<rt>ㄅㄨˊ</rt></ruby><ruby>過<rt>ㄍㄨㄛˋ</rt></ruby><ruby>氣<rt>ㄑㄧˋ</rt></ruby>", ex: "Feel suffocating.（覺得喘不過氣）" },
      { en: "chains", type: "名詞", ph: "/tʃeɪnz/", zh: "<ruby>鎖<rt>ㄙㄨㄛˇ</rt></ruby><ruby>鏈<rt>ㄌㄧㄢˋ</rt></ruby>", ex: "Break chains.（打破鎖鏈）" },
      { en: "dangerous", type: "形容詞", ph: "/ˈdeɪndʒərəs/", zh: "<ruby>危<rt>ㄨㄟˊ</rt></ruby><ruby>險<rt>ㄒㄧㄢˇ</rt></ruby>", ex: "Too dangerous.（太危險）" },
      { en: "weightless", type: "形容詞", ph: "/ˈweɪtləs/", zh: "<ruby>沒<rt>ㄇㄟˊ</rt></ruby><ruby>有<rt>ㄧㄡˇ</rt></ruby><ruby>重<rt>ㄓㄨㄥˋ</rt></ruby><ruby>量<rt>ㄌㄧㄤˋ</rt></ruby>", ex: "Weightless feel.（無重力感）" },
      { en: "imposter", type: "名詞", ph: "/ɪmˈpɑːstər/", zh: "<ruby>冒<rt>ㄇㄠˋ</rt></ruby><ruby>牌<rt>ㄆㄞˊ</rt></ruby><ruby>者<rt>ㄓㄜˇ</rt></ruby>", ex: "Not an imposter.（不是冒牌者）" },
      { en: "monster", type: "名詞", ph: "/ˈmɑːnstər/", zh: "<ruby>怪<rt>ㄍㄨㄞˋ</rt></ruby><ruby>物<rt>ㄨˋ</rt></ruby>", ex: "Scary monster.（可怕的怪物）" },
      { en: "trust", type: "動詞", ph: "/trʌst/", zh: "<ruby>信<rt>ㄒㄧㄣˋ</rt></ruby><ruby>任<rt>ㄖㄣˋ</rt></ruby>", ex: "Trust me.（相信我）" },
      { en: "heal", type: "動詞", ph: "/hiːl/", zh: "<ruby>療<rt>ㄌㄧㄠˊ</rt></ruby><ruby>癒<rt>ㄩˋ</rt></ruby>", ex: "Heal together.（一起療癒）" }
    ],
    mission: "聽到 <b>free</b> 雙手張開像翅膀 🕊️；聽到 <b>brave</b> 比一個加油的拳頭 💪；副歌 <b>we could be free</b> 全家大聲唱！"
  }
];
